# Code generated by packages/sdk-generator. DO NOT EDIT.
# Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
"""Account tax lines operations (``client.qbd.account_tax_lines``)."""

from __future__ import annotations

from functools import cached_property

from ..._base_client import Op
from ..._handles import AsyncRequestHandle, RequestHandle
from ..._resource import AsyncResource, Resource
from ..._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from ...types import AccountTaxLineList

_QBD_ACCOUNT_TAX_LINES_LIST = Op(
    "qbd.accountTaxLines.list",
    write=False,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)


class QbdAccountTaxLinesResourceWithRawResponse:
    """``client.qbd.account_tax_lines.with_raw_response``: the same methods, returning ``RawResponse[T]`` with status, headers and request ID."""

    def __init__(self, resource: QbdAccountTaxLinesResource) -> None:
        self.list = to_raw_response_wrapper(resource.list)


class QbdAccountTaxLinesEnqueue(Resource):
    """``client.qbd.account_tax_lines.enqueue``: the async-capable operations in async mode, returning request handles."""

    def list(
        self,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[AccountTaxLineList]:
        """List account tax lines, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the AccountTaxLineList.

        Operation ``qbd.accountTaxLines.list``: ``GET /v1/quickbooks-desktop/account-tax-lines``.

        Args:
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.accountTaxLines.list request.
        """
        return self._client._enqueue(
            _QBD_ACCOUNT_TAX_LINES_LIST,
            "GET",
            "/v1/quickbooks-desktop/account-tax-lines",
            cast_to=AccountTaxLineList.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )


class QbdAccountTaxLinesResource(Resource):
    """Account tax lines operations (``client.qbd.account_tax_lines``)."""

    @cached_property
    def with_raw_response(self) -> QbdAccountTaxLinesResourceWithRawResponse:
        """The same methods, returning ``RawResponse[T]`` (status code, headers, request ID and ``parse()``)."""
        return QbdAccountTaxLinesResourceWithRawResponse(self)

    @cached_property
    def enqueue(self) -> QbdAccountTaxLinesEnqueue:
        """The async-capable operations in async mode (``Prefer: respond-async``), returning request handles."""
        return QbdAccountTaxLinesEnqueue(self._client)

    def list(
        self,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> AccountTaxLineList:
        """List account tax lines.

        Returns the account tax lines that match your filters. QuickBooks has no cursor for this list, so the response contains every matching account tax line at once.

        Operation ``qbd.accountTaxLines.list``: ``GET /v1/quickbooks-desktop/account-tax-lines``.

        Args:
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The AccountTaxLineList object.
        """
        return self._client._request(
            _QBD_ACCOUNT_TAX_LINES_LIST,
            "GET",
            "/v1/quickbooks-desktop/account-tax-lines",
            cast_to=AccountTaxLineList.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )


class AsyncQbdAccountTaxLinesResourceWithRawResponse:
    """``async_client.qbd.account_tax_lines.with_raw_response``: the same methods, returning ``RawResponse[T]`` with status, headers and request ID."""

    def __init__(self, resource: AsyncQbdAccountTaxLinesResource) -> None:
        self.list = async_to_raw_response_wrapper(resource.list)


class AsyncQbdAccountTaxLinesEnqueue(AsyncResource):
    """``async_client.qbd.account_tax_lines.enqueue``: the async-capable operations in async mode, returning request handles."""

    async def list(
        self,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[AccountTaxLineList]:
        """List account tax lines, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the AccountTaxLineList.

        Operation ``qbd.accountTaxLines.list``: ``GET /v1/quickbooks-desktop/account-tax-lines``.

        Args:
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.accountTaxLines.list request.
        """
        return await self._client._enqueue(
            _QBD_ACCOUNT_TAX_LINES_LIST,
            "GET",
            "/v1/quickbooks-desktop/account-tax-lines",
            cast_to=AccountTaxLineList.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )


class AsyncQbdAccountTaxLinesResource(AsyncResource):
    """Account tax lines operations (``client.qbd.account_tax_lines``)."""

    @cached_property
    def with_raw_response(self) -> AsyncQbdAccountTaxLinesResourceWithRawResponse:
        """The same methods, returning ``RawResponse[T]`` (status code, headers, request ID and ``parse()``)."""
        return AsyncQbdAccountTaxLinesResourceWithRawResponse(self)

    @cached_property
    def enqueue(self) -> AsyncQbdAccountTaxLinesEnqueue:
        """The async-capable operations in async mode (``Prefer: respond-async``), returning request handles."""
        return AsyncQbdAccountTaxLinesEnqueue(self._client)

    async def list(
        self,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> AccountTaxLineList:
        """List account tax lines.

        Returns the account tax lines that match your filters. QuickBooks has no cursor for this list, so the response contains every matching account tax line at once.

        Operation ``qbd.accountTaxLines.list``: ``GET /v1/quickbooks-desktop/account-tax-lines``.

        Args:
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The AccountTaxLineList object.
        """
        return await self._client._request(
            _QBD_ACCOUNT_TAX_LINES_LIST,
            "GET",
            "/v1/quickbooks-desktop/account-tax-lines",
            cast_to=AccountTaxLineList.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )
