# Code generated by packages/sdk-generator. DO NOT EDIT.
# Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
"""Checks operations (``client.qbd.checks``)."""

from __future__ import annotations

import datetime as _dt
from collections.abc import Sequence
from functools import cached_property

from ..._base_client import Op
from ..._handles import AsyncRequestHandle, RequestHandle
from ..._pagination import AsyncCursorPager, CursorPager
from ..._resource import AsyncResource, Resource
from ..._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from ..._types import NOT_GIVEN, NotGiven
from ..._wire import DateOrDateTime
from ..._wire import path_param as _pp
from ...types import (
    AddressCreateInput,
    AddressUpdateInput,
    ApplyCheckToTxnInput,
    Check,
    CheckDeleted,
    CheckVoided,
    DateMacro,
    ExpenseLineCreateInput,
    ExpenseLineUpdateInput,
    ItemGroupLineCreateInput,
    ItemGroupLineUpdateInput,
    ItemLineCreateInput,
    ItemLineUpdateInput,
)

_QBD_CHECKS_CREATE = Op(
    "qbd.checks.create",
    write=True,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_CHECKS_DELETE = Op(
    "qbd.checks.delete",
    write=True,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_CHECKS_LIST = Op(
    "qbd.checks.list",
    write=False,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_CHECKS_RETRIEVE = Op(
    "qbd.checks.retrieve",
    write=False,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_CHECKS_UPDATE = Op(
    "qbd.checks.update",
    write=True,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_CHECKS_VOID = Op(
    "qbd.checks.void",
    write=True,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)


class QbdChecksResourceWithRawResponse:
    """``client.qbd.checks.with_raw_response``: the same methods, returning ``RawResponse[T]`` with status, headers and request ID."""

    def __init__(self, resource: QbdChecksResource) -> None:
        self.create = to_raw_response_wrapper(resource.create)
        self.delete = to_raw_response_wrapper(resource.delete)
        self.retrieve = to_raw_response_wrapper(resource.retrieve)
        self.update = to_raw_response_wrapper(resource.update)
        self.void = to_raw_response_wrapper(resource.void)


class QbdChecksEnqueue(Resource):
    """``client.qbd.checks.enqueue``: the async-capable operations in async mode, returning request handles."""

    def create(
        self,
        *,
        bank_account_id: str,
        payee_id: str | NotGiven = NOT_GIVEN,
        ref_number: str | NotGiven = NOT_GIVEN,
        transaction_date: _dt.date | NotGiven = NOT_GIVEN,
        memo: str | NotGiven = NOT_GIVEN,
        address: AddressCreateInput | NotGiven = NOT_GIVEN,
        is_queued_for_print: bool | NotGiven = NOT_GIVEN,
        exchange_rate: float | NotGiven = NOT_GIVEN,
        external_id: str | NotGiven = NOT_GIVEN,
        apply_to_transactions: Sequence[ApplyCheckToTxnInput] | NotGiven = NOT_GIVEN,
        expense_lines: Sequence[ExpenseLineCreateInput] | NotGiven = NOT_GIVEN,
        item_lines: Sequence[ItemLineCreateInput] | NotGiven = NOT_GIVEN,
        item_group_lines: Sequence[ItemGroupLineCreateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[Check]:
        """Create a check, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the Check.

        Operation ``qbd.checks.create``: ``POST /v1/quickbooks-desktop/checks``.

        Args:
            bank_account_id: ID of the bank account for this check.
            payee_id: ID of the payee for this check.
            ref_number: Reference number of this check, such as an invoice or check number. Case-sensitive.
            transaction_date: Date of this check (YYYY-MM-DD).
            memo: Internal memo for this check; shown in reports, not on printed forms.
            address: Address details for this check.
            is_queued_for_print: Whether this check is in the queue of forms to print.
            exchange_rate: Exchange rate from this check's currency to the home currency.
            external_id: Your own UUID for this check, stored by QuickBooks so you can match records with your system.
            apply_to_transactions: Apply to transactions entries for this check.
            expense_lines: Expense lines entries for this check.
            item_lines: Item lines entries for this check.
            item_group_lines: Item group lines entries for this check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.checks.create request.
        """
        return self._client._enqueue(
            _QBD_CHECKS_CREATE,
            "POST",
            "/v1/quickbooks-desktop/checks",
            cast_to=Check.from_wire,
            body={
                "bankAccountId": bank_account_id,
                "payeeId": payee_id,
                "refNumber": ref_number,
                "transactionDate": transaction_date,
                "memo": memo,
                "address": address,
                "isQueuedForPrint": is_queued_for_print,
                "exchangeRate": exchange_rate,
                "externalId": external_id,
                "applyToTransactions": apply_to_transactions,
                "expenseLines": expense_lines,
                "itemLines": item_lines,
                "itemGroupLines": item_group_lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def delete(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[CheckDeleted]:
        """Delete a check, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the CheckDeleted.

        Operation ``qbd.checks.delete``: ``DELETE /v1/quickbooks-desktop/checks/{id}``.

        Args:
            id: QuickBooks ID of the check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.checks.delete request.
        """
        return self._client._enqueue(
            _QBD_CHECKS_DELETE,
            "DELETE",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id),
            cast_to=CheckDeleted.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[Check]:
        """Retrieve a check, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the Check.

        Operation ``qbd.checks.retrieve``: ``GET /v1/quickbooks-desktop/checks/{id}``.

        Args:
            id: QuickBooks ID of the check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.checks.retrieve request.
        """
        return self._client._enqueue(
            _QBD_CHECKS_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id),
            cast_to=Check.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def update(
        self,
        id: str,
        *,
        revision_number: str,
        bank_account_id: str | NotGiven = NOT_GIVEN,
        payee_id: str | NotGiven = NOT_GIVEN,
        ref_number: str | NotGiven | None = NOT_GIVEN,
        transaction_date: _dt.date | NotGiven = NOT_GIVEN,
        memo: str | NotGiven | None = NOT_GIVEN,
        address: AddressUpdateInput | NotGiven = NOT_GIVEN,
        is_queued_for_print: bool | NotGiven = NOT_GIVEN,
        exchange_rate: float | NotGiven = NOT_GIVEN,
        apply_to_transactions: Sequence[ApplyCheckToTxnInput] | NotGiven = NOT_GIVEN,
        clear_expense_lines: bool | NotGiven = NOT_GIVEN,
        expense_lines: Sequence[ExpenseLineUpdateInput] | NotGiven = NOT_GIVEN,
        clear_item_lines: bool | NotGiven = NOT_GIVEN,
        item_lines: Sequence[ItemLineUpdateInput] | NotGiven = NOT_GIVEN,
        item_group_lines: Sequence[ItemGroupLineUpdateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[Check]:
        """Update a check, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the Check.

        Operation ``qbd.checks.update``: ``POST /v1/quickbooks-desktop/checks/{id}``.

        Args:
            id: QuickBooks ID of the check.
            revision_number: Current revision of this check. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
            bank_account_id: ID of the bank account for this check.
            payee_id: ID of the payee for this check.
            ref_number: Reference number of this check, such as an invoice or check number. Case-sensitive. Pass ``None`` to clear it.
            transaction_date: Date of this check (YYYY-MM-DD).
            memo: Internal memo for this check; shown in reports, not on printed forms. Pass ``None`` to clear it.
            address: Address details for this check.
            is_queued_for_print: Whether this check is in the queue of forms to print.
            exchange_rate: Exchange rate from this check's currency to the home currency.
            apply_to_transactions: Apply to transactions entries for this check.
            clear_expense_lines: Clear expense lines of this check. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged.
            expense_lines: Expense lines entries for this check. When present, replaces this array: keep an existing entry by sending its id (an id alone leaves it unchanged), add one with id "-1"; existing entries you leave out are deleted. Omit the array to keep these entries unchanged, also when you send itemLines or itemGroupLines: the API then reads the check first and keeps every existing entry of each omitted array by ID. An empty array deletes them all, as long as the check keeps at least one line.
            clear_item_lines: Clear item lines of this check. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged.
            item_lines: Item lines entries for this check. When present, replaces this array: keep an existing entry by sending its id (an id alone leaves it unchanged), add one with id "-1"; existing entries you leave out are deleted. Omit the array to keep these entries unchanged, also when you send expenseLines or itemGroupLines: the API then reads the check first and keeps every existing entry of each omitted array by ID. An empty array deletes them all, as long as the check keeps at least one line.
            item_group_lines: Item group lines entries for this check. When present, replaces this array: keep an existing entry by sending its id (an id alone leaves it unchanged), add one with id "-1"; existing entries you leave out are deleted. Omit the array to keep these entries unchanged, also when you send expenseLines or itemLines: the API then reads the check first and keeps every existing entry of each omitted array by ID. An empty array deletes them all, as long as the check keeps at least one line.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.checks.update request.
        """
        return self._client._enqueue(
            _QBD_CHECKS_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id),
            cast_to=Check.from_wire,
            body={
                "revisionNumber": revision_number,
                "bankAccountId": bank_account_id,
                "payeeId": payee_id,
                "refNumber": ref_number,
                "transactionDate": transaction_date,
                "memo": memo,
                "address": address,
                "isQueuedForPrint": is_queued_for_print,
                "exchangeRate": exchange_rate,
                "applyToTransactions": apply_to_transactions,
                "clearExpenseLines": clear_expense_lines,
                "expenseLines": expense_lines,
                "clearItemLines": clear_item_lines,
                "itemLines": item_lines,
                "itemGroupLines": item_group_lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def void(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[CheckVoided]:
        """Void a check, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the CheckVoided.

        Operation ``qbd.checks.void``: ``POST /v1/quickbooks-desktop/checks/{id}/void``.

        Args:
            id: QuickBooks ID of the check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.checks.void request.
        """
        return self._client._enqueue(
            _QBD_CHECKS_VOID,
            "POST",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id) + "/void",
            cast_to=CheckVoided.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )


class QbdChecksResource(Resource):
    """Checks operations (``client.qbd.checks``)."""

    @cached_property
    def with_raw_response(self) -> QbdChecksResourceWithRawResponse:
        """The same methods, returning ``RawResponse[T]`` (status code, headers, request ID and ``parse()``)."""
        return QbdChecksResourceWithRawResponse(self)

    @cached_property
    def enqueue(self) -> QbdChecksEnqueue:
        """The async-capable operations in async mode (``Prefer: respond-async``), returning request handles."""
        return QbdChecksEnqueue(self._client)

    def create(
        self,
        *,
        bank_account_id: str,
        payee_id: str | NotGiven = NOT_GIVEN,
        ref_number: str | NotGiven = NOT_GIVEN,
        transaction_date: _dt.date | NotGiven = NOT_GIVEN,
        memo: str | NotGiven = NOT_GIVEN,
        address: AddressCreateInput | NotGiven = NOT_GIVEN,
        is_queued_for_print: bool | NotGiven = NOT_GIVEN,
        exchange_rate: float | NotGiven = NOT_GIVEN,
        external_id: str | NotGiven = NOT_GIVEN,
        apply_to_transactions: Sequence[ApplyCheckToTxnInput] | NotGiven = NOT_GIVEN,
        expense_lines: Sequence[ExpenseLineCreateInput] | NotGiven = NOT_GIVEN,
        item_lines: Sequence[ItemLineCreateInput] | NotGiven = NOT_GIVEN,
        item_group_lines: Sequence[ItemGroupLineCreateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> Check:
        """Create a check.

        Creates a check in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second check (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).

        Operation ``qbd.checks.create``: ``POST /v1/quickbooks-desktop/checks``.

        Args:
            bank_account_id: ID of the bank account for this check.
            payee_id: ID of the payee for this check.
            ref_number: Reference number of this check, such as an invoice or check number. Case-sensitive.
            transaction_date: Date of this check (YYYY-MM-DD).
            memo: Internal memo for this check; shown in reports, not on printed forms.
            address: Address details for this check.
            is_queued_for_print: Whether this check is in the queue of forms to print.
            exchange_rate: Exchange rate from this check's currency to the home currency.
            external_id: Your own UUID for this check, stored by QuickBooks so you can match records with your system.
            apply_to_transactions: Apply to transactions entries for this check.
            expense_lines: Expense lines entries for this check.
            item_lines: Item lines entries for this check.
            item_group_lines: Item group lines entries for this check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The Check object.
        """
        return self._client._request(
            _QBD_CHECKS_CREATE,
            "POST",
            "/v1/quickbooks-desktop/checks",
            cast_to=Check.from_wire,
            body={
                "bankAccountId": bank_account_id,
                "payeeId": payee_id,
                "refNumber": ref_number,
                "transactionDate": transaction_date,
                "memo": memo,
                "address": address,
                "isQueuedForPrint": is_queued_for_print,
                "exchangeRate": exchange_rate,
                "externalId": external_id,
                "applyToTransactions": apply_to_transactions,
                "expenseLines": expense_lines,
                "itemLines": item_lines,
                "itemGroupLines": item_group_lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def delete(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CheckDeleted:
        """Delete a check.

        Permanently deletes a check. Deleting cannot be undone. Deleted transactions remain visible for 90 days through the deleted-transactions list. Send an `Idempotency-Key` to make retries safe.

        Operation ``qbd.checks.delete``: ``DELETE /v1/quickbooks-desktop/checks/{id}``.

        Args:
            id: QuickBooks ID of the check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The CheckDeleted object.
        """
        return self._client._request(
            _QBD_CHECKS_DELETE,
            "DELETE",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id),
            cast_to=CheckDeleted.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        ref_numbers: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        transaction_date_from: _dt.date | NotGiven = NOT_GIVEN,
        transaction_date_to: _dt.date | NotGiven = NOT_GIVEN,
        transaction_date_macro: DateMacro | NotGiven = NOT_GIVEN,
        payee_ids: Sequence[str] | NotGiven = NOT_GIVEN,
        account_ids: Sequence[str] | NotGiven = NOT_GIVEN,
        ref_number_starts_with: str | NotGiven = NOT_GIVEN,
        ref_number_contains: str | NotGiven = NOT_GIVEN,
        ref_number_ends_with: str | NotGiven = NOT_GIVEN,
        ref_number_from: str | NotGiven = NOT_GIVEN,
        ref_number_to: str | NotGiven = NOT_GIVEN,
        currency_ids: Sequence[str] | NotGiven = NOT_GIVEN,
        include_line_items: bool | NotGiven = NOT_GIVEN,
        include_linked_transactions: bool | NotGiven = NOT_GIVEN,
        cursor: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CursorPager[Check]:
        """List checks.

        Returns the checks that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).

        Operation ``qbd.checks.list``: ``GET /v1/quickbooks-desktop/checks``.

        Iterate to get every item across pages (the next page is requested only when the iteration needs it, or in the background once a page has been held for 2 seconds), or call ``first_page()``, ``iter_pages()`` or ``list_all()``. Raises ``CursorExpiredError`` if QuickBooks drops the iterator; the list is never restarted silently.

        Args:
            ids: Return only the checks with these QuickBooks IDs. Cannot be combined with refNumbers, updatedAfter, updatedBefore, transactionDateFrom, transactionDateTo, transactionDateMacro, payeeIds, accountIds, refNumberStartsWith, refNumberContains, refNumberEndsWith, refNumberFrom, refNumberTo, currencyIds. Returns every match in one page (`nextCursor` is null); limit is ignored.
            ref_numbers: Return only checks with these reference numbers (case-insensitive). Cannot be combined with ids, updatedAfter, updatedBefore, transactionDateFrom, transactionDateTo, transactionDateMacro, payeeIds, accountIds, refNumberStartsWith, refNumberContains, refNumberEndsWith, refNumberFrom, refNumberTo, currencyIds. Returns every match in one page (`nextCursor` is null); limit is ignored.
            limit: Maximum number of checks per page, 1 to 150. Ignored with ids, refNumbers, which return every match in one page. Default: ``150``.
            updated_after: Return checks changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, refNumbers, transactionDateFrom, transactionDateTo, transactionDateMacro.
            updated_before: Return checks changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, refNumbers, transactionDateFrom, transactionDateTo, transactionDateMacro.
            transaction_date_from: Return checks dated on or after this date (YYYY-MM-DD). Cannot be combined with ids, refNumbers, updatedAfter, updatedBefore, transactionDateMacro.
            transaction_date_to: Return checks dated on or before this date (YYYY-MM-DD). Cannot be combined with ids, refNumbers, updatedAfter, updatedBefore, transactionDateMacro.
            transaction_date_macro: Relative date range such as this_month, used instead of explicit dates. Cannot be combined with ids, refNumbers, updatedAfter, updatedBefore, transactionDateFrom, transactionDateTo.
            payee_ids: Return only checks linked to these payee IDs. Cannot be combined with ids, refNumbers.
            account_ids: Return only checks that use these account IDs. Cannot be combined with ids, refNumbers.
            ref_number_starts_with: Return checks whose reference number starts with this text (case-insensitive). Cannot be combined with ids, refNumbers, refNumberFrom, refNumberTo.
            ref_number_contains: Return checks whose reference number contains this text (case-insensitive). Cannot be combined with ids, refNumbers, refNumberFrom, refNumberTo.
            ref_number_ends_with: Return checks whose reference number ends with this text (case-insensitive). Cannot be combined with ids, refNumbers, refNumberFrom, refNumberTo.
            ref_number_from: Return checks whose reference number sorts at or after this value. Cannot be combined with ids, refNumbers, refNumberStartsWith, refNumberContains, refNumberEndsWith.
            ref_number_to: Return checks whose reference number sorts at or before this value. Cannot be combined with ids, refNumbers, refNumberStartsWith, refNumberContains, refNumberEndsWith.
            currency_ids: Return only checks in these currency IDs. Cannot be combined with ids, refNumbers.
            include_line_items: Whether to include line items on each check. Defaults to true. Default: ``true``.
            include_linked_transactions: Whether to include transactions linked to each check, such as payments. Default: ``false``.
            cursor: Cursor from the previous page's nextCursor. Send it with no other filters to fetch the next page.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            A pager over Check objects. Nothing is fetched until you iterate.
        """
        return self._client._paginate(
            _QBD_CHECKS_LIST,
            "/v1/quickbooks-desktop/checks",
            query={
                "ids": ids,
                "refNumbers": ref_numbers,
                "limit": limit,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "transactionDateFrom": transaction_date_from,
                "transactionDateTo": transaction_date_to,
                "transactionDateMacro": transaction_date_macro,
                "payeeIds": payee_ids,
                "accountIds": account_ids,
                "refNumberStartsWith": ref_number_starts_with,
                "refNumberContains": ref_number_contains,
                "refNumberEndsWith": ref_number_ends_with,
                "refNumberFrom": ref_number_from,
                "refNumberTo": ref_number_to,
                "currencyIds": currency_ids,
                "includeLineItems": include_line_items,
                "includeLinkedTransactions": include_linked_transactions,
                "cursor": cursor,
            },
            parse_item=Check.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> Check:
        """Retrieve a check.

        Returns one check by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.

        Operation ``qbd.checks.retrieve``: ``GET /v1/quickbooks-desktop/checks/{id}``.

        Args:
            id: QuickBooks ID of the check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The Check object.
        """
        return self._client._request(
            _QBD_CHECKS_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id),
            cast_to=Check.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def update(
        self,
        id: str,
        *,
        revision_number: str,
        bank_account_id: str | NotGiven = NOT_GIVEN,
        payee_id: str | NotGiven = NOT_GIVEN,
        ref_number: str | NotGiven | None = NOT_GIVEN,
        transaction_date: _dt.date | NotGiven = NOT_GIVEN,
        memo: str | NotGiven | None = NOT_GIVEN,
        address: AddressUpdateInput | NotGiven = NOT_GIVEN,
        is_queued_for_print: bool | NotGiven = NOT_GIVEN,
        exchange_rate: float | NotGiven = NOT_GIVEN,
        apply_to_transactions: Sequence[ApplyCheckToTxnInput] | NotGiven = NOT_GIVEN,
        clear_expense_lines: bool | NotGiven = NOT_GIVEN,
        expense_lines: Sequence[ExpenseLineUpdateInput] | NotGiven = NOT_GIVEN,
        clear_item_lines: bool | NotGiven = NOT_GIVEN,
        item_lines: Sequence[ItemLineUpdateInput] | NotGiven = NOT_GIVEN,
        item_group_lines: Sequence[ItemGroupLineUpdateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> Check:
        """Update a check.

        Changes the fields you send on an existing check and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the check, reapply your change and send the new revision. Sending a line array replaces all existing lines of that kind. Line arrays you omit stay unchanged: when you send only some of them, the API first reads the transaction (a separate read in the request log) and keeps the omitted lines by ID, because QuickBooks would otherwise delete them. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).

        Operation ``qbd.checks.update``: ``POST /v1/quickbooks-desktop/checks/{id}``.

        Args:
            id: QuickBooks ID of the check.
            revision_number: Current revision of this check. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
            bank_account_id: ID of the bank account for this check.
            payee_id: ID of the payee for this check.
            ref_number: Reference number of this check, such as an invoice or check number. Case-sensitive. Pass ``None`` to clear it.
            transaction_date: Date of this check (YYYY-MM-DD).
            memo: Internal memo for this check; shown in reports, not on printed forms. Pass ``None`` to clear it.
            address: Address details for this check.
            is_queued_for_print: Whether this check is in the queue of forms to print.
            exchange_rate: Exchange rate from this check's currency to the home currency.
            apply_to_transactions: Apply to transactions entries for this check.
            clear_expense_lines: Clear expense lines of this check. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged.
            expense_lines: Expense lines entries for this check. When present, replaces this array: keep an existing entry by sending its id (an id alone leaves it unchanged), add one with id "-1"; existing entries you leave out are deleted. Omit the array to keep these entries unchanged, also when you send itemLines or itemGroupLines: the API then reads the check first and keeps every existing entry of each omitted array by ID. An empty array deletes them all, as long as the check keeps at least one line.
            clear_item_lines: Clear item lines of this check. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged.
            item_lines: Item lines entries for this check. When present, replaces this array: keep an existing entry by sending its id (an id alone leaves it unchanged), add one with id "-1"; existing entries you leave out are deleted. Omit the array to keep these entries unchanged, also when you send expenseLines or itemGroupLines: the API then reads the check first and keeps every existing entry of each omitted array by ID. An empty array deletes them all, as long as the check keeps at least one line.
            item_group_lines: Item group lines entries for this check. When present, replaces this array: keep an existing entry by sending its id (an id alone leaves it unchanged), add one with id "-1"; existing entries you leave out are deleted. Omit the array to keep these entries unchanged, also when you send expenseLines or itemLines: the API then reads the check first and keeps every existing entry of each omitted array by ID. An empty array deletes them all, as long as the check keeps at least one line.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The Check object.
        """
        return self._client._request(
            _QBD_CHECKS_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id),
            cast_to=Check.from_wire,
            body={
                "revisionNumber": revision_number,
                "bankAccountId": bank_account_id,
                "payeeId": payee_id,
                "refNumber": ref_number,
                "transactionDate": transaction_date,
                "memo": memo,
                "address": address,
                "isQueuedForPrint": is_queued_for_print,
                "exchangeRate": exchange_rate,
                "applyToTransactions": apply_to_transactions,
                "clearExpenseLines": clear_expense_lines,
                "expenseLines": expense_lines,
                "clearItemLines": clear_item_lines,
                "itemLines": item_lines,
                "itemGroupLines": item_group_lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def void(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CheckVoided:
        """Void a check.

        Voids a check: QuickBooks keeps the record but sets its amounts to zero. Use void instead of delete when the check must stay in the audit trail. Send an `Idempotency-Key` to make retries safe.

        Operation ``qbd.checks.void``: ``POST /v1/quickbooks-desktop/checks/{id}/void``.

        Args:
            id: QuickBooks ID of the check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The CheckVoided object.
        """
        return self._client._request(
            _QBD_CHECKS_VOID,
            "POST",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id) + "/void",
            cast_to=CheckVoided.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )


class AsyncQbdChecksResourceWithRawResponse:
    """``async_client.qbd.checks.with_raw_response``: the same methods, returning ``RawResponse[T]`` with status, headers and request ID."""

    def __init__(self, resource: AsyncQbdChecksResource) -> None:
        self.create = async_to_raw_response_wrapper(resource.create)
        self.delete = async_to_raw_response_wrapper(resource.delete)
        self.retrieve = async_to_raw_response_wrapper(resource.retrieve)
        self.update = async_to_raw_response_wrapper(resource.update)
        self.void = async_to_raw_response_wrapper(resource.void)


class AsyncQbdChecksEnqueue(AsyncResource):
    """``async_client.qbd.checks.enqueue``: the async-capable operations in async mode, returning request handles."""

    async def create(
        self,
        *,
        bank_account_id: str,
        payee_id: str | NotGiven = NOT_GIVEN,
        ref_number: str | NotGiven = NOT_GIVEN,
        transaction_date: _dt.date | NotGiven = NOT_GIVEN,
        memo: str | NotGiven = NOT_GIVEN,
        address: AddressCreateInput | NotGiven = NOT_GIVEN,
        is_queued_for_print: bool | NotGiven = NOT_GIVEN,
        exchange_rate: float | NotGiven = NOT_GIVEN,
        external_id: str | NotGiven = NOT_GIVEN,
        apply_to_transactions: Sequence[ApplyCheckToTxnInput] | NotGiven = NOT_GIVEN,
        expense_lines: Sequence[ExpenseLineCreateInput] | NotGiven = NOT_GIVEN,
        item_lines: Sequence[ItemLineCreateInput] | NotGiven = NOT_GIVEN,
        item_group_lines: Sequence[ItemGroupLineCreateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[Check]:
        """Create a check, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the Check.

        Operation ``qbd.checks.create``: ``POST /v1/quickbooks-desktop/checks``.

        Args:
            bank_account_id: ID of the bank account for this check.
            payee_id: ID of the payee for this check.
            ref_number: Reference number of this check, such as an invoice or check number. Case-sensitive.
            transaction_date: Date of this check (YYYY-MM-DD).
            memo: Internal memo for this check; shown in reports, not on printed forms.
            address: Address details for this check.
            is_queued_for_print: Whether this check is in the queue of forms to print.
            exchange_rate: Exchange rate from this check's currency to the home currency.
            external_id: Your own UUID for this check, stored by QuickBooks so you can match records with your system.
            apply_to_transactions: Apply to transactions entries for this check.
            expense_lines: Expense lines entries for this check.
            item_lines: Item lines entries for this check.
            item_group_lines: Item group lines entries for this check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.checks.create request.
        """
        return await self._client._enqueue(
            _QBD_CHECKS_CREATE,
            "POST",
            "/v1/quickbooks-desktop/checks",
            cast_to=Check.from_wire,
            body={
                "bankAccountId": bank_account_id,
                "payeeId": payee_id,
                "refNumber": ref_number,
                "transactionDate": transaction_date,
                "memo": memo,
                "address": address,
                "isQueuedForPrint": is_queued_for_print,
                "exchangeRate": exchange_rate,
                "externalId": external_id,
                "applyToTransactions": apply_to_transactions,
                "expenseLines": expense_lines,
                "itemLines": item_lines,
                "itemGroupLines": item_group_lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def delete(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[CheckDeleted]:
        """Delete a check, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the CheckDeleted.

        Operation ``qbd.checks.delete``: ``DELETE /v1/quickbooks-desktop/checks/{id}``.

        Args:
            id: QuickBooks ID of the check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.checks.delete request.
        """
        return await self._client._enqueue(
            _QBD_CHECKS_DELETE,
            "DELETE",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id),
            cast_to=CheckDeleted.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[Check]:
        """Retrieve a check, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the Check.

        Operation ``qbd.checks.retrieve``: ``GET /v1/quickbooks-desktop/checks/{id}``.

        Args:
            id: QuickBooks ID of the check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.checks.retrieve request.
        """
        return await self._client._enqueue(
            _QBD_CHECKS_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id),
            cast_to=Check.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def update(
        self,
        id: str,
        *,
        revision_number: str,
        bank_account_id: str | NotGiven = NOT_GIVEN,
        payee_id: str | NotGiven = NOT_GIVEN,
        ref_number: str | NotGiven | None = NOT_GIVEN,
        transaction_date: _dt.date | NotGiven = NOT_GIVEN,
        memo: str | NotGiven | None = NOT_GIVEN,
        address: AddressUpdateInput | NotGiven = NOT_GIVEN,
        is_queued_for_print: bool | NotGiven = NOT_GIVEN,
        exchange_rate: float | NotGiven = NOT_GIVEN,
        apply_to_transactions: Sequence[ApplyCheckToTxnInput] | NotGiven = NOT_GIVEN,
        clear_expense_lines: bool | NotGiven = NOT_GIVEN,
        expense_lines: Sequence[ExpenseLineUpdateInput] | NotGiven = NOT_GIVEN,
        clear_item_lines: bool | NotGiven = NOT_GIVEN,
        item_lines: Sequence[ItemLineUpdateInput] | NotGiven = NOT_GIVEN,
        item_group_lines: Sequence[ItemGroupLineUpdateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[Check]:
        """Update a check, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the Check.

        Operation ``qbd.checks.update``: ``POST /v1/quickbooks-desktop/checks/{id}``.

        Args:
            id: QuickBooks ID of the check.
            revision_number: Current revision of this check. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
            bank_account_id: ID of the bank account for this check.
            payee_id: ID of the payee for this check.
            ref_number: Reference number of this check, such as an invoice or check number. Case-sensitive. Pass ``None`` to clear it.
            transaction_date: Date of this check (YYYY-MM-DD).
            memo: Internal memo for this check; shown in reports, not on printed forms. Pass ``None`` to clear it.
            address: Address details for this check.
            is_queued_for_print: Whether this check is in the queue of forms to print.
            exchange_rate: Exchange rate from this check's currency to the home currency.
            apply_to_transactions: Apply to transactions entries for this check.
            clear_expense_lines: Clear expense lines of this check. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged.
            expense_lines: Expense lines entries for this check. When present, replaces this array: keep an existing entry by sending its id (an id alone leaves it unchanged), add one with id "-1"; existing entries you leave out are deleted. Omit the array to keep these entries unchanged, also when you send itemLines or itemGroupLines: the API then reads the check first and keeps every existing entry of each omitted array by ID. An empty array deletes them all, as long as the check keeps at least one line.
            clear_item_lines: Clear item lines of this check. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged.
            item_lines: Item lines entries for this check. When present, replaces this array: keep an existing entry by sending its id (an id alone leaves it unchanged), add one with id "-1"; existing entries you leave out are deleted. Omit the array to keep these entries unchanged, also when you send expenseLines or itemGroupLines: the API then reads the check first and keeps every existing entry of each omitted array by ID. An empty array deletes them all, as long as the check keeps at least one line.
            item_group_lines: Item group lines entries for this check. When present, replaces this array: keep an existing entry by sending its id (an id alone leaves it unchanged), add one with id "-1"; existing entries you leave out are deleted. Omit the array to keep these entries unchanged, also when you send expenseLines or itemLines: the API then reads the check first and keeps every existing entry of each omitted array by ID. An empty array deletes them all, as long as the check keeps at least one line.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.checks.update request.
        """
        return await self._client._enqueue(
            _QBD_CHECKS_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id),
            cast_to=Check.from_wire,
            body={
                "revisionNumber": revision_number,
                "bankAccountId": bank_account_id,
                "payeeId": payee_id,
                "refNumber": ref_number,
                "transactionDate": transaction_date,
                "memo": memo,
                "address": address,
                "isQueuedForPrint": is_queued_for_print,
                "exchangeRate": exchange_rate,
                "applyToTransactions": apply_to_transactions,
                "clearExpenseLines": clear_expense_lines,
                "expenseLines": expense_lines,
                "clearItemLines": clear_item_lines,
                "itemLines": item_lines,
                "itemGroupLines": item_group_lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def void(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[CheckVoided]:
        """Void a check, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the CheckVoided.

        Operation ``qbd.checks.void``: ``POST /v1/quickbooks-desktop/checks/{id}/void``.

        Args:
            id: QuickBooks ID of the check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.checks.void request.
        """
        return await self._client._enqueue(
            _QBD_CHECKS_VOID,
            "POST",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id) + "/void",
            cast_to=CheckVoided.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )


class AsyncQbdChecksResource(AsyncResource):
    """Checks operations (``client.qbd.checks``)."""

    @cached_property
    def with_raw_response(self) -> AsyncQbdChecksResourceWithRawResponse:
        """The same methods, returning ``RawResponse[T]`` (status code, headers, request ID and ``parse()``)."""
        return AsyncQbdChecksResourceWithRawResponse(self)

    @cached_property
    def enqueue(self) -> AsyncQbdChecksEnqueue:
        """The async-capable operations in async mode (``Prefer: respond-async``), returning request handles."""
        return AsyncQbdChecksEnqueue(self._client)

    async def create(
        self,
        *,
        bank_account_id: str,
        payee_id: str | NotGiven = NOT_GIVEN,
        ref_number: str | NotGiven = NOT_GIVEN,
        transaction_date: _dt.date | NotGiven = NOT_GIVEN,
        memo: str | NotGiven = NOT_GIVEN,
        address: AddressCreateInput | NotGiven = NOT_GIVEN,
        is_queued_for_print: bool | NotGiven = NOT_GIVEN,
        exchange_rate: float | NotGiven = NOT_GIVEN,
        external_id: str | NotGiven = NOT_GIVEN,
        apply_to_transactions: Sequence[ApplyCheckToTxnInput] | NotGiven = NOT_GIVEN,
        expense_lines: Sequence[ExpenseLineCreateInput] | NotGiven = NOT_GIVEN,
        item_lines: Sequence[ItemLineCreateInput] | NotGiven = NOT_GIVEN,
        item_group_lines: Sequence[ItemGroupLineCreateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> Check:
        """Create a check.

        Creates a check in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second check (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).

        Operation ``qbd.checks.create``: ``POST /v1/quickbooks-desktop/checks``.

        Args:
            bank_account_id: ID of the bank account for this check.
            payee_id: ID of the payee for this check.
            ref_number: Reference number of this check, such as an invoice or check number. Case-sensitive.
            transaction_date: Date of this check (YYYY-MM-DD).
            memo: Internal memo for this check; shown in reports, not on printed forms.
            address: Address details for this check.
            is_queued_for_print: Whether this check is in the queue of forms to print.
            exchange_rate: Exchange rate from this check's currency to the home currency.
            external_id: Your own UUID for this check, stored by QuickBooks so you can match records with your system.
            apply_to_transactions: Apply to transactions entries for this check.
            expense_lines: Expense lines entries for this check.
            item_lines: Item lines entries for this check.
            item_group_lines: Item group lines entries for this check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The Check object.
        """
        return await self._client._request(
            _QBD_CHECKS_CREATE,
            "POST",
            "/v1/quickbooks-desktop/checks",
            cast_to=Check.from_wire,
            body={
                "bankAccountId": bank_account_id,
                "payeeId": payee_id,
                "refNumber": ref_number,
                "transactionDate": transaction_date,
                "memo": memo,
                "address": address,
                "isQueuedForPrint": is_queued_for_print,
                "exchangeRate": exchange_rate,
                "externalId": external_id,
                "applyToTransactions": apply_to_transactions,
                "expenseLines": expense_lines,
                "itemLines": item_lines,
                "itemGroupLines": item_group_lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def delete(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CheckDeleted:
        """Delete a check.

        Permanently deletes a check. Deleting cannot be undone. Deleted transactions remain visible for 90 days through the deleted-transactions list. Send an `Idempotency-Key` to make retries safe.

        Operation ``qbd.checks.delete``: ``DELETE /v1/quickbooks-desktop/checks/{id}``.

        Args:
            id: QuickBooks ID of the check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The CheckDeleted object.
        """
        return await self._client._request(
            _QBD_CHECKS_DELETE,
            "DELETE",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id),
            cast_to=CheckDeleted.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        ref_numbers: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        transaction_date_from: _dt.date | NotGiven = NOT_GIVEN,
        transaction_date_to: _dt.date | NotGiven = NOT_GIVEN,
        transaction_date_macro: DateMacro | NotGiven = NOT_GIVEN,
        payee_ids: Sequence[str] | NotGiven = NOT_GIVEN,
        account_ids: Sequence[str] | NotGiven = NOT_GIVEN,
        ref_number_starts_with: str | NotGiven = NOT_GIVEN,
        ref_number_contains: str | NotGiven = NOT_GIVEN,
        ref_number_ends_with: str | NotGiven = NOT_GIVEN,
        ref_number_from: str | NotGiven = NOT_GIVEN,
        ref_number_to: str | NotGiven = NOT_GIVEN,
        currency_ids: Sequence[str] | NotGiven = NOT_GIVEN,
        include_line_items: bool | NotGiven = NOT_GIVEN,
        include_linked_transactions: bool | NotGiven = NOT_GIVEN,
        cursor: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> AsyncCursorPager[Check]:
        """List checks.

        Returns the checks that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).

        Operation ``qbd.checks.list``: ``GET /v1/quickbooks-desktop/checks``.

        Iterate with ``async for`` to get every item across pages (the next page is requested only when the iteration needs it, or in the background once a page has been held for 2 seconds), or call ``first_page()``, ``iter_pages()`` or ``list_all()``. Raises ``CursorExpiredError`` if QuickBooks drops the iterator; the list is never restarted silently.

        Args:
            ids: Return only the checks with these QuickBooks IDs. Cannot be combined with refNumbers, updatedAfter, updatedBefore, transactionDateFrom, transactionDateTo, transactionDateMacro, payeeIds, accountIds, refNumberStartsWith, refNumberContains, refNumberEndsWith, refNumberFrom, refNumberTo, currencyIds. Returns every match in one page (`nextCursor` is null); limit is ignored.
            ref_numbers: Return only checks with these reference numbers (case-insensitive). Cannot be combined with ids, updatedAfter, updatedBefore, transactionDateFrom, transactionDateTo, transactionDateMacro, payeeIds, accountIds, refNumberStartsWith, refNumberContains, refNumberEndsWith, refNumberFrom, refNumberTo, currencyIds. Returns every match in one page (`nextCursor` is null); limit is ignored.
            limit: Maximum number of checks per page, 1 to 150. Ignored with ids, refNumbers, which return every match in one page. Default: ``150``.
            updated_after: Return checks changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, refNumbers, transactionDateFrom, transactionDateTo, transactionDateMacro.
            updated_before: Return checks changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, refNumbers, transactionDateFrom, transactionDateTo, transactionDateMacro.
            transaction_date_from: Return checks dated on or after this date (YYYY-MM-DD). Cannot be combined with ids, refNumbers, updatedAfter, updatedBefore, transactionDateMacro.
            transaction_date_to: Return checks dated on or before this date (YYYY-MM-DD). Cannot be combined with ids, refNumbers, updatedAfter, updatedBefore, transactionDateMacro.
            transaction_date_macro: Relative date range such as this_month, used instead of explicit dates. Cannot be combined with ids, refNumbers, updatedAfter, updatedBefore, transactionDateFrom, transactionDateTo.
            payee_ids: Return only checks linked to these payee IDs. Cannot be combined with ids, refNumbers.
            account_ids: Return only checks that use these account IDs. Cannot be combined with ids, refNumbers.
            ref_number_starts_with: Return checks whose reference number starts with this text (case-insensitive). Cannot be combined with ids, refNumbers, refNumberFrom, refNumberTo.
            ref_number_contains: Return checks whose reference number contains this text (case-insensitive). Cannot be combined with ids, refNumbers, refNumberFrom, refNumberTo.
            ref_number_ends_with: Return checks whose reference number ends with this text (case-insensitive). Cannot be combined with ids, refNumbers, refNumberFrom, refNumberTo.
            ref_number_from: Return checks whose reference number sorts at or after this value. Cannot be combined with ids, refNumbers, refNumberStartsWith, refNumberContains, refNumberEndsWith.
            ref_number_to: Return checks whose reference number sorts at or before this value. Cannot be combined with ids, refNumbers, refNumberStartsWith, refNumberContains, refNumberEndsWith.
            currency_ids: Return only checks in these currency IDs. Cannot be combined with ids, refNumbers.
            include_line_items: Whether to include line items on each check. Defaults to true. Default: ``true``.
            include_linked_transactions: Whether to include transactions linked to each check, such as payments. Default: ``false``.
            cursor: Cursor from the previous page's nextCursor. Send it with no other filters to fetch the next page.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            A pager over Check objects. Nothing is fetched until you iterate.
        """
        return self._client._paginate(
            _QBD_CHECKS_LIST,
            "/v1/quickbooks-desktop/checks",
            query={
                "ids": ids,
                "refNumbers": ref_numbers,
                "limit": limit,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "transactionDateFrom": transaction_date_from,
                "transactionDateTo": transaction_date_to,
                "transactionDateMacro": transaction_date_macro,
                "payeeIds": payee_ids,
                "accountIds": account_ids,
                "refNumberStartsWith": ref_number_starts_with,
                "refNumberContains": ref_number_contains,
                "refNumberEndsWith": ref_number_ends_with,
                "refNumberFrom": ref_number_from,
                "refNumberTo": ref_number_to,
                "currencyIds": currency_ids,
                "includeLineItems": include_line_items,
                "includeLinkedTransactions": include_linked_transactions,
                "cursor": cursor,
            },
            parse_item=Check.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> Check:
        """Retrieve a check.

        Returns one check by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.

        Operation ``qbd.checks.retrieve``: ``GET /v1/quickbooks-desktop/checks/{id}``.

        Args:
            id: QuickBooks ID of the check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The Check object.
        """
        return await self._client._request(
            _QBD_CHECKS_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id),
            cast_to=Check.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def update(
        self,
        id: str,
        *,
        revision_number: str,
        bank_account_id: str | NotGiven = NOT_GIVEN,
        payee_id: str | NotGiven = NOT_GIVEN,
        ref_number: str | NotGiven | None = NOT_GIVEN,
        transaction_date: _dt.date | NotGiven = NOT_GIVEN,
        memo: str | NotGiven | None = NOT_GIVEN,
        address: AddressUpdateInput | NotGiven = NOT_GIVEN,
        is_queued_for_print: bool | NotGiven = NOT_GIVEN,
        exchange_rate: float | NotGiven = NOT_GIVEN,
        apply_to_transactions: Sequence[ApplyCheckToTxnInput] | NotGiven = NOT_GIVEN,
        clear_expense_lines: bool | NotGiven = NOT_GIVEN,
        expense_lines: Sequence[ExpenseLineUpdateInput] | NotGiven = NOT_GIVEN,
        clear_item_lines: bool | NotGiven = NOT_GIVEN,
        item_lines: Sequence[ItemLineUpdateInput] | NotGiven = NOT_GIVEN,
        item_group_lines: Sequence[ItemGroupLineUpdateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> Check:
        """Update a check.

        Changes the fields you send on an existing check and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the check, reapply your change and send the new revision. Sending a line array replaces all existing lines of that kind. Line arrays you omit stay unchanged: when you send only some of them, the API first reads the transaction (a separate read in the request log) and keeps the omitted lines by ID, because QuickBooks would otherwise delete them. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).

        Operation ``qbd.checks.update``: ``POST /v1/quickbooks-desktop/checks/{id}``.

        Args:
            id: QuickBooks ID of the check.
            revision_number: Current revision of this check. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
            bank_account_id: ID of the bank account for this check.
            payee_id: ID of the payee for this check.
            ref_number: Reference number of this check, such as an invoice or check number. Case-sensitive. Pass ``None`` to clear it.
            transaction_date: Date of this check (YYYY-MM-DD).
            memo: Internal memo for this check; shown in reports, not on printed forms. Pass ``None`` to clear it.
            address: Address details for this check.
            is_queued_for_print: Whether this check is in the queue of forms to print.
            exchange_rate: Exchange rate from this check's currency to the home currency.
            apply_to_transactions: Apply to transactions entries for this check.
            clear_expense_lines: Clear expense lines of this check. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged.
            expense_lines: Expense lines entries for this check. When present, replaces this array: keep an existing entry by sending its id (an id alone leaves it unchanged), add one with id "-1"; existing entries you leave out are deleted. Omit the array to keep these entries unchanged, also when you send itemLines or itemGroupLines: the API then reads the check first and keeps every existing entry of each omitted array by ID. An empty array deletes them all, as long as the check keeps at least one line.
            clear_item_lines: Clear item lines of this check. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged.
            item_lines: Item lines entries for this check. When present, replaces this array: keep an existing entry by sending its id (an id alone leaves it unchanged), add one with id "-1"; existing entries you leave out are deleted. Omit the array to keep these entries unchanged, also when you send expenseLines or itemGroupLines: the API then reads the check first and keeps every existing entry of each omitted array by ID. An empty array deletes them all, as long as the check keeps at least one line.
            item_group_lines: Item group lines entries for this check. When present, replaces this array: keep an existing entry by sending its id (an id alone leaves it unchanged), add one with id "-1"; existing entries you leave out are deleted. Omit the array to keep these entries unchanged, also when you send expenseLines or itemLines: the API then reads the check first and keeps every existing entry of each omitted array by ID. An empty array deletes them all, as long as the check keeps at least one line.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The Check object.
        """
        return await self._client._request(
            _QBD_CHECKS_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id),
            cast_to=Check.from_wire,
            body={
                "revisionNumber": revision_number,
                "bankAccountId": bank_account_id,
                "payeeId": payee_id,
                "refNumber": ref_number,
                "transactionDate": transaction_date,
                "memo": memo,
                "address": address,
                "isQueuedForPrint": is_queued_for_print,
                "exchangeRate": exchange_rate,
                "applyToTransactions": apply_to_transactions,
                "clearExpenseLines": clear_expense_lines,
                "expenseLines": expense_lines,
                "clearItemLines": clear_item_lines,
                "itemLines": item_lines,
                "itemGroupLines": item_group_lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def void(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CheckVoided:
        """Void a check.

        Voids a check: QuickBooks keeps the record but sets its amounts to zero. Use void instead of delete when the check must stay in the audit trail. Send an `Idempotency-Key` to make retries safe.

        Operation ``qbd.checks.void``: ``POST /v1/quickbooks-desktop/checks/{id}/void``.

        Args:
            id: QuickBooks ID of the check.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The CheckVoided object.
        """
        return await self._client._request(
            _QBD_CHECKS_VOID,
            "POST",
            "/v1/quickbooks-desktop/checks/" + _pp("id", id) + "/void",
            cast_to=CheckVoided.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )
