# Code generated by packages/sdk-generator. DO NOT EDIT.
# Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:b5774d24bc8154ccc2acb85370ae27581a072c3f5070a529111ee2dd26f103b9
"""Customer types operations (``client.qbd.customer_types``)."""

from __future__ import annotations

from collections.abc import Sequence
from functools import cached_property

from ..._base_client import Op
from ..._handles import AsyncRequestHandle, RequestHandle
from ..._resource import AsyncResource, Resource
from ..._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from ..._types import NOT_GIVEN, NotGiven
from ..._wire import DateOrDateTime
from ..._wire import path_param as _pp
from ...types import ActiveStatus, CustomerType, CustomerTypeList

_QBD_CUSTOMER_TYPES_CREATE = Op(
    "qbd.customerTypes.create",
    write=True,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_CUSTOMER_TYPES_LIST = Op(
    "qbd.customerTypes.list",
    write=False,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_CUSTOMER_TYPES_RETRIEVE = Op(
    "qbd.customerTypes.retrieve",
    write=False,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)


class QbdCustomerTypesResourceWithRawResponse:
    """``client.qbd.customer_types.with_raw_response``: the same methods, returning ``RawResponse[T]`` with status, headers and request ID."""

    def __init__(self, resource: QbdCustomerTypesResource) -> None:
        self.create = to_raw_response_wrapper(resource.create)
        self.list = to_raw_response_wrapper(resource.list)
        self.retrieve = to_raw_response_wrapper(resource.retrieve)


class QbdCustomerTypesEnqueue(Resource):
    """``client.qbd.customer_types.enqueue``: the async-capable operations in async mode, returning request handles."""

    def create(
        self,
        *,
        name: str,
        is_active: bool | NotGiven = NOT_GIVEN,
        parent_id: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[CustomerType]:
        """Create a customer type, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the CustomerType.

        Operation ``qbd.customerTypes.create``: ``POST /v1/quickbooks-desktop/customer-types``.

        Args:
            name: Name of this customer type, unique within its parent level.
            is_active: Whether this customer type is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            parent_id: ID of the parent object, making this customer type a child in the hierarchy.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.customerTypes.create request.
        """
        return self._client._enqueue(
            _QBD_CUSTOMER_TYPES_CREATE,
            "POST",
            "/v1/quickbooks-desktop/customer-types",
            cast_to=CustomerType.from_wire,
            body={
                "name": name,
                "isActive": is_active,
                "parentId": parent_id,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        full_names: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        status: ActiveStatus | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        name_starts_with: str | NotGiven = NOT_GIVEN,
        name_contains: str | NotGiven = NOT_GIVEN,
        name_ends_with: str | NotGiven = NOT_GIVEN,
        name_from: str | NotGiven = NOT_GIVEN,
        name_to: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[CustomerTypeList]:
        """List customer types, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the CustomerTypeList.

        Operation ``qbd.customerTypes.list``: ``GET /v1/quickbooks-desktop/customer-types``.

        Args:
            ids: Return only the customer types with these QuickBooks IDs. Cannot be combined with fullNames, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            full_names: Return only the customer types with these full names (case-insensitive, including parent names separated by colons). Cannot be combined with ids, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            limit: Maximum number of customer types to return. Cannot be combined with ids, fullNames.
            status: Filter customer types by active state. Defaults to active ones only. Cannot be combined with ids, fullNames.
            updated_after: Return customer types changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, fullNames.
            updated_before: Return customer types changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, fullNames.
            name_starts_with: Return customer types whose name starts with this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_contains: Return customer types whose name contains this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_ends_with: Return customer types whose name ends with this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_from: Return customer types whose name sorts at or after this value. Cannot be combined with ids, fullNames, nameStartsWith, nameContains, nameEndsWith.
            name_to: Return customer types whose name sorts at or before this value. Cannot be combined with ids, fullNames, nameStartsWith, nameContains, nameEndsWith.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.customerTypes.list request.
        """
        return self._client._enqueue(
            _QBD_CUSTOMER_TYPES_LIST,
            "GET",
            "/v1/quickbooks-desktop/customer-types",
            cast_to=CustomerTypeList.from_wire,
            query={
                "ids": ids,
                "fullNames": full_names,
                "limit": limit,
                "status": status,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "nameStartsWith": name_starts_with,
                "nameContains": name_contains,
                "nameEndsWith": name_ends_with,
                "nameFrom": name_from,
                "nameTo": name_to,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[CustomerType]:
        """Retrieve a customer type, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the CustomerType.

        Operation ``qbd.customerTypes.retrieve``: ``GET /v1/quickbooks-desktop/customer-types/{id}``.

        Args:
            id: QuickBooks ID of the customer type.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.customerTypes.retrieve request.
        """
        return self._client._enqueue(
            _QBD_CUSTOMER_TYPES_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/customer-types/" + _pp("id", id),
            cast_to=CustomerType.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )


class QbdCustomerTypesResource(Resource):
    """Customer types operations (``client.qbd.customer_types``)."""

    @cached_property
    def with_raw_response(self) -> QbdCustomerTypesResourceWithRawResponse:
        """The same methods, returning ``RawResponse[T]`` (status code, headers, request ID and ``parse()``)."""
        return QbdCustomerTypesResourceWithRawResponse(self)

    @cached_property
    def enqueue(self) -> QbdCustomerTypesEnqueue:
        """The async-capable operations in async mode (``Prefer: respond-async``), returning request handles."""
        return QbdCustomerTypesEnqueue(self._client)

    def create(
        self,
        *,
        name: str,
        is_active: bool | NotGiven = NOT_GIVEN,
        parent_id: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CustomerType:
        """Create a customer type.

        Creates a customer type in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second customer type (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).

        Operation ``qbd.customerTypes.create``: ``POST /v1/quickbooks-desktop/customer-types``.

        Args:
            name: Name of this customer type, unique within its parent level.
            is_active: Whether this customer type is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            parent_id: ID of the parent object, making this customer type a child in the hierarchy.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The CustomerType object.
        """
        return self._client._request(
            _QBD_CUSTOMER_TYPES_CREATE,
            "POST",
            "/v1/quickbooks-desktop/customer-types",
            cast_to=CustomerType.from_wire,
            body={
                "name": name,
                "isActive": is_active,
                "parentId": parent_id,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        full_names: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        status: ActiveStatus | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        name_starts_with: str | NotGiven = NOT_GIVEN,
        name_contains: str | NotGiven = NOT_GIVEN,
        name_ends_with: str | NotGiven = NOT_GIVEN,
        name_from: str | NotGiven = NOT_GIVEN,
        name_to: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CustomerTypeList:
        """List customer types.

        Returns the customer types that match your filters. QuickBooks has no cursor for this list, so the response contains every matching customer type at once.

        Operation ``qbd.customerTypes.list``: ``GET /v1/quickbooks-desktop/customer-types``.

        Args:
            ids: Return only the customer types with these QuickBooks IDs. Cannot be combined with fullNames, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            full_names: Return only the customer types with these full names (case-insensitive, including parent names separated by colons). Cannot be combined with ids, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            limit: Maximum number of customer types to return. Cannot be combined with ids, fullNames.
            status: Filter customer types by active state. Defaults to active ones only. Cannot be combined with ids, fullNames.
            updated_after: Return customer types changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, fullNames.
            updated_before: Return customer types changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, fullNames.
            name_starts_with: Return customer types whose name starts with this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_contains: Return customer types whose name contains this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_ends_with: Return customer types whose name ends with this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_from: Return customer types whose name sorts at or after this value. Cannot be combined with ids, fullNames, nameStartsWith, nameContains, nameEndsWith.
            name_to: Return customer types whose name sorts at or before this value. Cannot be combined with ids, fullNames, nameStartsWith, nameContains, nameEndsWith.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The CustomerTypeList object.
        """
        return self._client._request(
            _QBD_CUSTOMER_TYPES_LIST,
            "GET",
            "/v1/quickbooks-desktop/customer-types",
            cast_to=CustomerTypeList.from_wire,
            query={
                "ids": ids,
                "fullNames": full_names,
                "limit": limit,
                "status": status,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "nameStartsWith": name_starts_with,
                "nameContains": name_contains,
                "nameEndsWith": name_ends_with,
                "nameFrom": name_from,
                "nameTo": name_to,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CustomerType:
        """Retrieve a customer type.

        Returns one customer type by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.

        Operation ``qbd.customerTypes.retrieve``: ``GET /v1/quickbooks-desktop/customer-types/{id}``.

        Args:
            id: QuickBooks ID of the customer type.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The CustomerType object.
        """
        return self._client._request(
            _QBD_CUSTOMER_TYPES_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/customer-types/" + _pp("id", id),
            cast_to=CustomerType.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )


class AsyncQbdCustomerTypesResourceWithRawResponse:
    """``async_client.qbd.customer_types.with_raw_response``: the same methods, returning ``RawResponse[T]`` with status, headers and request ID."""

    def __init__(self, resource: AsyncQbdCustomerTypesResource) -> None:
        self.create = async_to_raw_response_wrapper(resource.create)
        self.list = async_to_raw_response_wrapper(resource.list)
        self.retrieve = async_to_raw_response_wrapper(resource.retrieve)


class AsyncQbdCustomerTypesEnqueue(AsyncResource):
    """``async_client.qbd.customer_types.enqueue``: the async-capable operations in async mode, returning request handles."""

    async def create(
        self,
        *,
        name: str,
        is_active: bool | NotGiven = NOT_GIVEN,
        parent_id: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[CustomerType]:
        """Create a customer type, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the CustomerType.

        Operation ``qbd.customerTypes.create``: ``POST /v1/quickbooks-desktop/customer-types``.

        Args:
            name: Name of this customer type, unique within its parent level.
            is_active: Whether this customer type is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            parent_id: ID of the parent object, making this customer type a child in the hierarchy.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.customerTypes.create request.
        """
        return await self._client._enqueue(
            _QBD_CUSTOMER_TYPES_CREATE,
            "POST",
            "/v1/quickbooks-desktop/customer-types",
            cast_to=CustomerType.from_wire,
            body={
                "name": name,
                "isActive": is_active,
                "parentId": parent_id,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        full_names: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        status: ActiveStatus | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        name_starts_with: str | NotGiven = NOT_GIVEN,
        name_contains: str | NotGiven = NOT_GIVEN,
        name_ends_with: str | NotGiven = NOT_GIVEN,
        name_from: str | NotGiven = NOT_GIVEN,
        name_to: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[CustomerTypeList]:
        """List customer types, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the CustomerTypeList.

        Operation ``qbd.customerTypes.list``: ``GET /v1/quickbooks-desktop/customer-types``.

        Args:
            ids: Return only the customer types with these QuickBooks IDs. Cannot be combined with fullNames, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            full_names: Return only the customer types with these full names (case-insensitive, including parent names separated by colons). Cannot be combined with ids, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            limit: Maximum number of customer types to return. Cannot be combined with ids, fullNames.
            status: Filter customer types by active state. Defaults to active ones only. Cannot be combined with ids, fullNames.
            updated_after: Return customer types changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, fullNames.
            updated_before: Return customer types changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, fullNames.
            name_starts_with: Return customer types whose name starts with this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_contains: Return customer types whose name contains this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_ends_with: Return customer types whose name ends with this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_from: Return customer types whose name sorts at or after this value. Cannot be combined with ids, fullNames, nameStartsWith, nameContains, nameEndsWith.
            name_to: Return customer types whose name sorts at or before this value. Cannot be combined with ids, fullNames, nameStartsWith, nameContains, nameEndsWith.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.customerTypes.list request.
        """
        return await self._client._enqueue(
            _QBD_CUSTOMER_TYPES_LIST,
            "GET",
            "/v1/quickbooks-desktop/customer-types",
            cast_to=CustomerTypeList.from_wire,
            query={
                "ids": ids,
                "fullNames": full_names,
                "limit": limit,
                "status": status,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "nameStartsWith": name_starts_with,
                "nameContains": name_contains,
                "nameEndsWith": name_ends_with,
                "nameFrom": name_from,
                "nameTo": name_to,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[CustomerType]:
        """Retrieve a customer type, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the CustomerType.

        Operation ``qbd.customerTypes.retrieve``: ``GET /v1/quickbooks-desktop/customer-types/{id}``.

        Args:
            id: QuickBooks ID of the customer type.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.customerTypes.retrieve request.
        """
        return await self._client._enqueue(
            _QBD_CUSTOMER_TYPES_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/customer-types/" + _pp("id", id),
            cast_to=CustomerType.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )


class AsyncQbdCustomerTypesResource(AsyncResource):
    """Customer types operations (``client.qbd.customer_types``)."""

    @cached_property
    def with_raw_response(self) -> AsyncQbdCustomerTypesResourceWithRawResponse:
        """The same methods, returning ``RawResponse[T]`` (status code, headers, request ID and ``parse()``)."""
        return AsyncQbdCustomerTypesResourceWithRawResponse(self)

    @cached_property
    def enqueue(self) -> AsyncQbdCustomerTypesEnqueue:
        """The async-capable operations in async mode (``Prefer: respond-async``), returning request handles."""
        return AsyncQbdCustomerTypesEnqueue(self._client)

    async def create(
        self,
        *,
        name: str,
        is_active: bool | NotGiven = NOT_GIVEN,
        parent_id: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CustomerType:
        """Create a customer type.

        Creates a customer type in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second customer type (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).

        Operation ``qbd.customerTypes.create``: ``POST /v1/quickbooks-desktop/customer-types``.

        Args:
            name: Name of this customer type, unique within its parent level.
            is_active: Whether this customer type is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            parent_id: ID of the parent object, making this customer type a child in the hierarchy.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The CustomerType object.
        """
        return await self._client._request(
            _QBD_CUSTOMER_TYPES_CREATE,
            "POST",
            "/v1/quickbooks-desktop/customer-types",
            cast_to=CustomerType.from_wire,
            body={
                "name": name,
                "isActive": is_active,
                "parentId": parent_id,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        full_names: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        status: ActiveStatus | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        name_starts_with: str | NotGiven = NOT_GIVEN,
        name_contains: str | NotGiven = NOT_GIVEN,
        name_ends_with: str | NotGiven = NOT_GIVEN,
        name_from: str | NotGiven = NOT_GIVEN,
        name_to: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CustomerTypeList:
        """List customer types.

        Returns the customer types that match your filters. QuickBooks has no cursor for this list, so the response contains every matching customer type at once.

        Operation ``qbd.customerTypes.list``: ``GET /v1/quickbooks-desktop/customer-types``.

        Args:
            ids: Return only the customer types with these QuickBooks IDs. Cannot be combined with fullNames, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            full_names: Return only the customer types with these full names (case-insensitive, including parent names separated by colons). Cannot be combined with ids, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            limit: Maximum number of customer types to return. Cannot be combined with ids, fullNames.
            status: Filter customer types by active state. Defaults to active ones only. Cannot be combined with ids, fullNames.
            updated_after: Return customer types changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, fullNames.
            updated_before: Return customer types changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, fullNames.
            name_starts_with: Return customer types whose name starts with this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_contains: Return customer types whose name contains this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_ends_with: Return customer types whose name ends with this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_from: Return customer types whose name sorts at or after this value. Cannot be combined with ids, fullNames, nameStartsWith, nameContains, nameEndsWith.
            name_to: Return customer types whose name sorts at or before this value. Cannot be combined with ids, fullNames, nameStartsWith, nameContains, nameEndsWith.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The CustomerTypeList object.
        """
        return await self._client._request(
            _QBD_CUSTOMER_TYPES_LIST,
            "GET",
            "/v1/quickbooks-desktop/customer-types",
            cast_to=CustomerTypeList.from_wire,
            query={
                "ids": ids,
                "fullNames": full_names,
                "limit": limit,
                "status": status,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "nameStartsWith": name_starts_with,
                "nameContains": name_contains,
                "nameEndsWith": name_ends_with,
                "nameFrom": name_from,
                "nameTo": name_to,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CustomerType:
        """Retrieve a customer type.

        Returns one customer type by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.

        Operation ``qbd.customerTypes.retrieve``: ``GET /v1/quickbooks-desktop/customer-types/{id}``.

        Args:
            id: QuickBooks ID of the customer type.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The CustomerType object.
        """
        return await self._client._request(
            _QBD_CUSTOMER_TYPES_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/customer-types/" + _pp("id", id),
            cast_to=CustomerType.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )
