# Code generated by packages/sdk-generator. DO NOT EDIT.
# Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:6f5ac28d7c33ac90aa7e2c15d88efd50e8e41c808bcc5489f0c8b1cb7833326a
"""Item groups operations (``client.qbd.item_groups``)."""

from __future__ import annotations

from collections.abc import Sequence
from functools import cached_property

from ..._base_client import Op
from ..._handles import AsyncRequestHandle, RequestHandle
from ..._pagination import AsyncCursorPager, CursorPager
from ..._resource import AsyncResource, Resource
from ..._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from ..._types import NOT_GIVEN, NotGiven
from ..._wire import DateOrDateTime
from ..._wire import path_param as _pp
from ...types import (
    ActiveStatus,
    BarcodeCreateInput,
    BarcodeUpdateInput,
    ItemGroup,
    ItemGroupMemberLineCreateInput,
    ItemGroupMemberLineUpdateInput,
)

_QBD_ITEM_GROUPS_CREATE = Op(
    "qbd.itemGroups.create",
    write=True,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_ITEM_GROUPS_LIST = Op(
    "qbd.itemGroups.list",
    write=False,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_ITEM_GROUPS_RETRIEVE = Op(
    "qbd.itemGroups.retrieve",
    write=False,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_ITEM_GROUPS_UPDATE = Op(
    "qbd.itemGroups.update",
    write=True,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)


class QbdItemGroupsResourceWithRawResponse:
    """``client.qbd.item_groups.with_raw_response``: the same methods, returning ``RawResponse[T]`` with status, headers and request ID."""

    def __init__(self, resource: QbdItemGroupsResource) -> None:
        self.create = to_raw_response_wrapper(resource.create)
        self.retrieve = to_raw_response_wrapper(resource.retrieve)
        self.update = to_raw_response_wrapper(resource.update)


class QbdItemGroupsEnqueue(Resource):
    """``client.qbd.item_groups.enqueue``: the async-capable operations in async mode, returning request handles."""

    def create(
        self,
        *,
        name: str,
        barcode: BarcodeCreateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven = NOT_GIVEN,
        unit_of_measure_set_id: str | NotGiven = NOT_GIVEN,
        should_print_items_in_group: bool | NotGiven = NOT_GIVEN,
        external_id: str | NotGiven = NOT_GIVEN,
        lines: Sequence[ItemGroupMemberLineCreateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[ItemGroup]:
        """Create an item group, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the ItemGroup.

        Operation ``qbd.itemGroups.create``: ``POST /v1/quickbooks-desktop/item-groups``.

        Args:
            name: Name of this item group, unique within its parent level.
            barcode: Barcode details for this item group.
            is_active: Whether this item group is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            description: Description of this item group.
            unit_of_measure_set_id: ID of the unit of measure set for this item group.
            should_print_items_in_group: Whether to print items in group.
            external_id: Your own UUID for this item group, stored by QuickBooks so you can match records with your system.
            lines: Line items of this item group.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.itemGroups.create request.
        """
        return self._client._enqueue(
            _QBD_ITEM_GROUPS_CREATE,
            "POST",
            "/v1/quickbooks-desktop/item-groups",
            cast_to=ItemGroup.from_wire,
            body={
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "description": description,
                "unitOfMeasureSetId": unit_of_measure_set_id,
                "shouldPrintItemsInGroup": should_print_items_in_group,
                "externalId": external_id,
                "lines": lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[ItemGroup]:
        """Retrieve an item group, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the ItemGroup.

        Operation ``qbd.itemGroups.retrieve``: ``GET /v1/quickbooks-desktop/item-groups/{id}``.

        Args:
            id: QuickBooks ID of the item group.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.itemGroups.retrieve request.
        """
        return self._client._enqueue(
            _QBD_ITEM_GROUPS_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/item-groups/" + _pp("id", id),
            cast_to=ItemGroup.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def update(
        self,
        id: str,
        *,
        revision_number: str,
        name: str | NotGiven = NOT_GIVEN,
        barcode: BarcodeUpdateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven | None = NOT_GIVEN,
        unit_of_measure_set_id: str | NotGiven = NOT_GIVEN,
        force_unit_of_measure_change: bool | NotGiven = NOT_GIVEN,
        should_print_items_in_group: bool | NotGiven = NOT_GIVEN,
        clear_item_lines: bool | NotGiven = NOT_GIVEN,
        lines: Sequence[ItemGroupMemberLineUpdateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[ItemGroup]:
        """Update an item group, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the ItemGroup.

        Operation ``qbd.itemGroups.update``: ``POST /v1/quickbooks-desktop/item-groups/{id}``.

        Args:
            id: QuickBooks ID of the item group.
            revision_number: Current revision of this item group. Send it unchanged when updating; a stale value is rejected.
            name: Name of this item group, unique within its parent level.
            barcode: Barcode details for this item group.
            is_active: Whether this item group is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            description: Description of this item group. Pass ``None`` to clear it.
            unit_of_measure_set_id: ID of the unit of measure set for this item group.
            force_unit_of_measure_change: Force unit of measure change of this item group.
            should_print_items_in_group: Whether to print items in group.
            clear_item_lines: Clear item lines of this item group. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged. Cannot be combined with lines.
            lines: Line items of this item group. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged. Cannot be combined with clearItemLines.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.itemGroups.update request.
        """
        return self._client._enqueue(
            _QBD_ITEM_GROUPS_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/item-groups/" + _pp("id", id),
            cast_to=ItemGroup.from_wire,
            body={
                "revisionNumber": revision_number,
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "description": description,
                "unitOfMeasureSetId": unit_of_measure_set_id,
                "forceUnitOfMeasureChange": force_unit_of_measure_change,
                "shouldPrintItemsInGroup": should_print_items_in_group,
                "clearItemLines": clear_item_lines,
                "lines": lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )


class QbdItemGroupsResource(Resource):
    """Item groups operations (``client.qbd.item_groups``)."""

    @cached_property
    def with_raw_response(self) -> QbdItemGroupsResourceWithRawResponse:
        """The same methods, returning ``RawResponse[T]`` (status code, headers, request ID and ``parse()``)."""
        return QbdItemGroupsResourceWithRawResponse(self)

    @cached_property
    def enqueue(self) -> QbdItemGroupsEnqueue:
        """The async-capable operations in async mode (``Prefer: respond-async``), returning request handles."""
        return QbdItemGroupsEnqueue(self._client)

    def create(
        self,
        *,
        name: str,
        barcode: BarcodeCreateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven = NOT_GIVEN,
        unit_of_measure_set_id: str | NotGiven = NOT_GIVEN,
        should_print_items_in_group: bool | NotGiven = NOT_GIVEN,
        external_id: str | NotGiven = NOT_GIVEN,
        lines: Sequence[ItemGroupMemberLineCreateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> ItemGroup:
        """Create an item group.

        Creates an item group in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second item group (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).

        Operation ``qbd.itemGroups.create``: ``POST /v1/quickbooks-desktop/item-groups``.

        Args:
            name: Name of this item group, unique within its parent level.
            barcode: Barcode details for this item group.
            is_active: Whether this item group is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            description: Description of this item group.
            unit_of_measure_set_id: ID of the unit of measure set for this item group.
            should_print_items_in_group: Whether to print items in group.
            external_id: Your own UUID for this item group, stored by QuickBooks so you can match records with your system.
            lines: Line items of this item group.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The ItemGroup object.
        """
        return self._client._request(
            _QBD_ITEM_GROUPS_CREATE,
            "POST",
            "/v1/quickbooks-desktop/item-groups",
            cast_to=ItemGroup.from_wire,
            body={
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "description": description,
                "unitOfMeasureSetId": unit_of_measure_set_id,
                "shouldPrintItemsInGroup": should_print_items_in_group,
                "externalId": external_id,
                "lines": lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        names: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        status: ActiveStatus | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        name_starts_with: str | NotGiven = NOT_GIVEN,
        name_contains: str | NotGiven = NOT_GIVEN,
        name_ends_with: str | NotGiven = NOT_GIVEN,
        name_from: str | NotGiven = NOT_GIVEN,
        name_to: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CursorPager[ItemGroup]:
        """List item groups.

        Returns the item groups that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).

        Operation ``qbd.itemGroups.list``: ``GET /v1/quickbooks-desktop/item-groups``.

        Iterate to get every item across pages (the next page is requested only when the iteration needs it, or in the background once a page has been held for 2 seconds), or call ``first_page()``, ``iter_pages()`` or ``list_all()``. Raises ``CursorExpiredError`` if QuickBooks drops the iterator; the list is never restarted silently.

        Args:
            ids: Return only the item groups with these QuickBooks IDs. Cannot be combined with names, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo. Returns every match in one page (`nextCursor` is null); limit is ignored.
            names: Return only the item groups with these names (case-insensitive). Cannot be combined with ids, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo. Returns every match in one page (`nextCursor` is null); limit is ignored.
            limit: Maximum number of item groups per page, 1 to 150. Ignored with ids, names, which return every match in one page. Default: ``150``.
            status: Filter item groups by active state. Defaults to active ones only. Cannot be combined with ids, names.
            updated_after: Return item groups changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
            updated_before: Return item groups changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
            name_starts_with: Return item groups whose name starts with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_contains: Return item groups whose name contains this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_ends_with: Return item groups whose name ends with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_from: Return item groups whose name sorts at or after this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
            name_to: Return item groups whose name sorts at or before this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            A pager over ItemGroup objects. Nothing is fetched until you iterate.
        """
        return self._client._paginate(
            _QBD_ITEM_GROUPS_LIST,
            "/v1/quickbooks-desktop/item-groups",
            query={
                "ids": ids,
                "names": names,
                "limit": limit,
                "status": status,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "nameStartsWith": name_starts_with,
                "nameContains": name_contains,
                "nameEndsWith": name_ends_with,
                "nameFrom": name_from,
                "nameTo": name_to,
            },
            parse_item=ItemGroup.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> ItemGroup:
        """Retrieve an item group.

        Returns one item group by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.

        Operation ``qbd.itemGroups.retrieve``: ``GET /v1/quickbooks-desktop/item-groups/{id}``.

        Args:
            id: QuickBooks ID of the item group.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The ItemGroup object.
        """
        return self._client._request(
            _QBD_ITEM_GROUPS_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/item-groups/" + _pp("id", id),
            cast_to=ItemGroup.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def update(
        self,
        id: str,
        *,
        revision_number: str,
        name: str | NotGiven = NOT_GIVEN,
        barcode: BarcodeUpdateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven | None = NOT_GIVEN,
        unit_of_measure_set_id: str | NotGiven = NOT_GIVEN,
        force_unit_of_measure_change: bool | NotGiven = NOT_GIVEN,
        should_print_items_in_group: bool | NotGiven = NOT_GIVEN,
        clear_item_lines: bool | NotGiven = NOT_GIVEN,
        lines: Sequence[ItemGroupMemberLineUpdateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> ItemGroup:
        """Update an item group.

        Changes the fields you send on an existing item group and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the item group, reapply your change and send the new revision. Sending a line array replaces all existing lines of that kind. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).

        Operation ``qbd.itemGroups.update``: ``POST /v1/quickbooks-desktop/item-groups/{id}``.

        Args:
            id: QuickBooks ID of the item group.
            revision_number: Current revision of this item group. Send it unchanged when updating; a stale value is rejected.
            name: Name of this item group, unique within its parent level.
            barcode: Barcode details for this item group.
            is_active: Whether this item group is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            description: Description of this item group. Pass ``None`` to clear it.
            unit_of_measure_set_id: ID of the unit of measure set for this item group.
            force_unit_of_measure_change: Force unit of measure change of this item group.
            should_print_items_in_group: Whether to print items in group.
            clear_item_lines: Clear item lines of this item group. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged. Cannot be combined with lines.
            lines: Line items of this item group. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged. Cannot be combined with clearItemLines.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The ItemGroup object.
        """
        return self._client._request(
            _QBD_ITEM_GROUPS_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/item-groups/" + _pp("id", id),
            cast_to=ItemGroup.from_wire,
            body={
                "revisionNumber": revision_number,
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "description": description,
                "unitOfMeasureSetId": unit_of_measure_set_id,
                "forceUnitOfMeasureChange": force_unit_of_measure_change,
                "shouldPrintItemsInGroup": should_print_items_in_group,
                "clearItemLines": clear_item_lines,
                "lines": lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )


class AsyncQbdItemGroupsResourceWithRawResponse:
    """``async_client.qbd.item_groups.with_raw_response``: the same methods, returning ``RawResponse[T]`` with status, headers and request ID."""

    def __init__(self, resource: AsyncQbdItemGroupsResource) -> None:
        self.create = async_to_raw_response_wrapper(resource.create)
        self.retrieve = async_to_raw_response_wrapper(resource.retrieve)
        self.update = async_to_raw_response_wrapper(resource.update)


class AsyncQbdItemGroupsEnqueue(AsyncResource):
    """``async_client.qbd.item_groups.enqueue``: the async-capable operations in async mode, returning request handles."""

    async def create(
        self,
        *,
        name: str,
        barcode: BarcodeCreateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven = NOT_GIVEN,
        unit_of_measure_set_id: str | NotGiven = NOT_GIVEN,
        should_print_items_in_group: bool | NotGiven = NOT_GIVEN,
        external_id: str | NotGiven = NOT_GIVEN,
        lines: Sequence[ItemGroupMemberLineCreateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[ItemGroup]:
        """Create an item group, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the ItemGroup.

        Operation ``qbd.itemGroups.create``: ``POST /v1/quickbooks-desktop/item-groups``.

        Args:
            name: Name of this item group, unique within its parent level.
            barcode: Barcode details for this item group.
            is_active: Whether this item group is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            description: Description of this item group.
            unit_of_measure_set_id: ID of the unit of measure set for this item group.
            should_print_items_in_group: Whether to print items in group.
            external_id: Your own UUID for this item group, stored by QuickBooks so you can match records with your system.
            lines: Line items of this item group.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.itemGroups.create request.
        """
        return await self._client._enqueue(
            _QBD_ITEM_GROUPS_CREATE,
            "POST",
            "/v1/quickbooks-desktop/item-groups",
            cast_to=ItemGroup.from_wire,
            body={
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "description": description,
                "unitOfMeasureSetId": unit_of_measure_set_id,
                "shouldPrintItemsInGroup": should_print_items_in_group,
                "externalId": external_id,
                "lines": lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[ItemGroup]:
        """Retrieve an item group, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the ItemGroup.

        Operation ``qbd.itemGroups.retrieve``: ``GET /v1/quickbooks-desktop/item-groups/{id}``.

        Args:
            id: QuickBooks ID of the item group.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.itemGroups.retrieve request.
        """
        return await self._client._enqueue(
            _QBD_ITEM_GROUPS_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/item-groups/" + _pp("id", id),
            cast_to=ItemGroup.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def update(
        self,
        id: str,
        *,
        revision_number: str,
        name: str | NotGiven = NOT_GIVEN,
        barcode: BarcodeUpdateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven | None = NOT_GIVEN,
        unit_of_measure_set_id: str | NotGiven = NOT_GIVEN,
        force_unit_of_measure_change: bool | NotGiven = NOT_GIVEN,
        should_print_items_in_group: bool | NotGiven = NOT_GIVEN,
        clear_item_lines: bool | NotGiven = NOT_GIVEN,
        lines: Sequence[ItemGroupMemberLineUpdateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[ItemGroup]:
        """Update an item group, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the ItemGroup.

        Operation ``qbd.itemGroups.update``: ``POST /v1/quickbooks-desktop/item-groups/{id}``.

        Args:
            id: QuickBooks ID of the item group.
            revision_number: Current revision of this item group. Send it unchanged when updating; a stale value is rejected.
            name: Name of this item group, unique within its parent level.
            barcode: Barcode details for this item group.
            is_active: Whether this item group is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            description: Description of this item group. Pass ``None`` to clear it.
            unit_of_measure_set_id: ID of the unit of measure set for this item group.
            force_unit_of_measure_change: Force unit of measure change of this item group.
            should_print_items_in_group: Whether to print items in group.
            clear_item_lines: Clear item lines of this item group. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged. Cannot be combined with lines.
            lines: Line items of this item group. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged. Cannot be combined with clearItemLines.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.itemGroups.update request.
        """
        return await self._client._enqueue(
            _QBD_ITEM_GROUPS_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/item-groups/" + _pp("id", id),
            cast_to=ItemGroup.from_wire,
            body={
                "revisionNumber": revision_number,
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "description": description,
                "unitOfMeasureSetId": unit_of_measure_set_id,
                "forceUnitOfMeasureChange": force_unit_of_measure_change,
                "shouldPrintItemsInGroup": should_print_items_in_group,
                "clearItemLines": clear_item_lines,
                "lines": lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )


class AsyncQbdItemGroupsResource(AsyncResource):
    """Item groups operations (``client.qbd.item_groups``)."""

    @cached_property
    def with_raw_response(self) -> AsyncQbdItemGroupsResourceWithRawResponse:
        """The same methods, returning ``RawResponse[T]`` (status code, headers, request ID and ``parse()``)."""
        return AsyncQbdItemGroupsResourceWithRawResponse(self)

    @cached_property
    def enqueue(self) -> AsyncQbdItemGroupsEnqueue:
        """The async-capable operations in async mode (``Prefer: respond-async``), returning request handles."""
        return AsyncQbdItemGroupsEnqueue(self._client)

    async def create(
        self,
        *,
        name: str,
        barcode: BarcodeCreateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven = NOT_GIVEN,
        unit_of_measure_set_id: str | NotGiven = NOT_GIVEN,
        should_print_items_in_group: bool | NotGiven = NOT_GIVEN,
        external_id: str | NotGiven = NOT_GIVEN,
        lines: Sequence[ItemGroupMemberLineCreateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> ItemGroup:
        """Create an item group.

        Creates an item group in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second item group (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).

        Operation ``qbd.itemGroups.create``: ``POST /v1/quickbooks-desktop/item-groups``.

        Args:
            name: Name of this item group, unique within its parent level.
            barcode: Barcode details for this item group.
            is_active: Whether this item group is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            description: Description of this item group.
            unit_of_measure_set_id: ID of the unit of measure set for this item group.
            should_print_items_in_group: Whether to print items in group.
            external_id: Your own UUID for this item group, stored by QuickBooks so you can match records with your system.
            lines: Line items of this item group.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The ItemGroup object.
        """
        return await self._client._request(
            _QBD_ITEM_GROUPS_CREATE,
            "POST",
            "/v1/quickbooks-desktop/item-groups",
            cast_to=ItemGroup.from_wire,
            body={
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "description": description,
                "unitOfMeasureSetId": unit_of_measure_set_id,
                "shouldPrintItemsInGroup": should_print_items_in_group,
                "externalId": external_id,
                "lines": lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        names: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        status: ActiveStatus | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        name_starts_with: str | NotGiven = NOT_GIVEN,
        name_contains: str | NotGiven = NOT_GIVEN,
        name_ends_with: str | NotGiven = NOT_GIVEN,
        name_from: str | NotGiven = NOT_GIVEN,
        name_to: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> AsyncCursorPager[ItemGroup]:
        """List item groups.

        Returns the item groups that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).

        Operation ``qbd.itemGroups.list``: ``GET /v1/quickbooks-desktop/item-groups``.

        Iterate with ``async for`` to get every item across pages (the next page is requested only when the iteration needs it, or in the background once a page has been held for 2 seconds), or call ``first_page()``, ``iter_pages()`` or ``list_all()``. Raises ``CursorExpiredError`` if QuickBooks drops the iterator; the list is never restarted silently.

        Args:
            ids: Return only the item groups with these QuickBooks IDs. Cannot be combined with names, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo. Returns every match in one page (`nextCursor` is null); limit is ignored.
            names: Return only the item groups with these names (case-insensitive). Cannot be combined with ids, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo. Returns every match in one page (`nextCursor` is null); limit is ignored.
            limit: Maximum number of item groups per page, 1 to 150. Ignored with ids, names, which return every match in one page. Default: ``150``.
            status: Filter item groups by active state. Defaults to active ones only. Cannot be combined with ids, names.
            updated_after: Return item groups changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
            updated_before: Return item groups changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
            name_starts_with: Return item groups whose name starts with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_contains: Return item groups whose name contains this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_ends_with: Return item groups whose name ends with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_from: Return item groups whose name sorts at or after this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
            name_to: Return item groups whose name sorts at or before this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            A pager over ItemGroup objects. Nothing is fetched until you iterate.
        """
        return self._client._paginate(
            _QBD_ITEM_GROUPS_LIST,
            "/v1/quickbooks-desktop/item-groups",
            query={
                "ids": ids,
                "names": names,
                "limit": limit,
                "status": status,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "nameStartsWith": name_starts_with,
                "nameContains": name_contains,
                "nameEndsWith": name_ends_with,
                "nameFrom": name_from,
                "nameTo": name_to,
            },
            parse_item=ItemGroup.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> ItemGroup:
        """Retrieve an item group.

        Returns one item group by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.

        Operation ``qbd.itemGroups.retrieve``: ``GET /v1/quickbooks-desktop/item-groups/{id}``.

        Args:
            id: QuickBooks ID of the item group.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The ItemGroup object.
        """
        return await self._client._request(
            _QBD_ITEM_GROUPS_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/item-groups/" + _pp("id", id),
            cast_to=ItemGroup.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def update(
        self,
        id: str,
        *,
        revision_number: str,
        name: str | NotGiven = NOT_GIVEN,
        barcode: BarcodeUpdateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven | None = NOT_GIVEN,
        unit_of_measure_set_id: str | NotGiven = NOT_GIVEN,
        force_unit_of_measure_change: bool | NotGiven = NOT_GIVEN,
        should_print_items_in_group: bool | NotGiven = NOT_GIVEN,
        clear_item_lines: bool | NotGiven = NOT_GIVEN,
        lines: Sequence[ItemGroupMemberLineUpdateInput] | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> ItemGroup:
        """Update an item group.

        Changes the fields you send on an existing item group and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the item group, reapply your change and send the new revision. Sending a line array replaces all existing lines of that kind. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).

        Operation ``qbd.itemGroups.update``: ``POST /v1/quickbooks-desktop/item-groups/{id}``.

        Args:
            id: QuickBooks ID of the item group.
            revision_number: Current revision of this item group. Send it unchanged when updating; a stale value is rejected.
            name: Name of this item group, unique within its parent level.
            barcode: Barcode details for this item group.
            is_active: Whether this item group is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            description: Description of this item group. Pass ``None`` to clear it.
            unit_of_measure_set_id: ID of the unit of measure set for this item group.
            force_unit_of_measure_change: Force unit of measure change of this item group.
            should_print_items_in_group: Whether to print items in group.
            clear_item_lines: Clear item lines of this item group. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged. Cannot be combined with lines.
            lines: Line items of this item group. Replaces every existing line when present: keep a line by sending its id, add one with id "-1", omit the array to leave lines unchanged. Cannot be combined with clearItemLines.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The ItemGroup object.
        """
        return await self._client._request(
            _QBD_ITEM_GROUPS_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/item-groups/" + _pp("id", id),
            cast_to=ItemGroup.from_wire,
            body={
                "revisionNumber": revision_number,
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "description": description,
                "unitOfMeasureSetId": unit_of_measure_set_id,
                "forceUnitOfMeasureChange": force_unit_of_measure_change,
                "shouldPrintItemsInGroup": should_print_items_in_group,
                "clearItemLines": clear_item_lines,
                "lines": lines,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )
