# Code generated by packages/sdk-generator. DO NOT EDIT.
# Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
"""Other charge items operations (``client.qbd.other_charge_items``)."""

from __future__ import annotations

from collections.abc import Sequence
from functools import cached_property

from ..._base_client import Op
from ..._handles import AsyncRequestHandle, RequestHandle
from ..._pagination import AsyncCursorPager, CursorPager
from ..._resource import AsyncResource, Resource
from ..._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from ..._types import NOT_GIVEN, NotGiven
from ..._wire import DateOrDateTime
from ..._wire import path_param as _pp
from ...types import (
    ActiveStatus,
    BarcodeCreateInput,
    BarcodeUpdateInput,
    OtherChargeItem,
    SalesAndPurchaseDetailCreateInput,
    SalesAndPurchaseDetailUpdateInput,
    SalesOrPurchaseDetailCreateInput,
    SalesOrPurchaseDetailUpdateInput,
)

_QBD_OTHER_CHARGE_ITEMS_CREATE = Op(
    "qbd.otherChargeItems.create",
    write=True,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_OTHER_CHARGE_ITEMS_LIST = Op(
    "qbd.otherChargeItems.list",
    write=False,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_OTHER_CHARGE_ITEMS_RETRIEVE = Op(
    "qbd.otherChargeItems.retrieve",
    write=False,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_OTHER_CHARGE_ITEMS_UPDATE = Op(
    "qbd.otherChargeItems.update",
    write=True,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)


class QbdOtherChargeItemsResourceWithRawResponse:
    """``client.qbd.other_charge_items.with_raw_response``: the same methods, returning ``RawResponse[T]`` with status, headers and request ID."""

    def __init__(self, resource: QbdOtherChargeItemsResource) -> None:
        self.create = to_raw_response_wrapper(resource.create)
        self.retrieve = to_raw_response_wrapper(resource.retrieve)
        self.update = to_raw_response_wrapper(resource.update)


class QbdOtherChargeItemsEnqueue(Resource):
    """``client.qbd.other_charge_items.enqueue``: the async-capable operations in async mode, returning request handles."""

    def create(
        self,
        *,
        name: str,
        barcode: BarcodeCreateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        class_id: str | NotGiven = NOT_GIVEN,
        parent_id: str | NotGiven = NOT_GIVEN,
        sales_tax_code_id: str | NotGiven = NOT_GIVEN,
        sales_or_purchase_details: SalesOrPurchaseDetailCreateInput | NotGiven = NOT_GIVEN,
        sales_and_purchase_details: SalesAndPurchaseDetailCreateInput | NotGiven = NOT_GIVEN,
        external_id: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[OtherChargeItem]:
        """Create an other charge item, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the OtherChargeItem.

        Operation ``qbd.otherChargeItems.create``: ``POST /v1/quickbooks-desktop/other-charge-items``.

        Args:
            name: Name of this other charge item, unique within its parent level.
            barcode: Barcode details for this other charge item.
            is_active: Whether this other charge item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            class_id: ID of the class for this other charge item.
            parent_id: ID of the parent object, making this other charge item a child in the hierarchy.
            sales_tax_code_id: ID of the sales tax code for this other charge item.
            sales_or_purchase_details: Sales or purchase details details for this other charge item. Cannot be combined with salesAndPurchaseDetails.
            sales_and_purchase_details: Sales and purchase details details for this other charge item. Cannot be combined with salesOrPurchaseDetails.
            external_id: Your own UUID for this other charge item, stored by QuickBooks so you can match records with your system.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.otherChargeItems.create request.
        """
        return self._client._enqueue(
            _QBD_OTHER_CHARGE_ITEMS_CREATE,
            "POST",
            "/v1/quickbooks-desktop/other-charge-items",
            cast_to=OtherChargeItem.from_wire,
            body={
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "classId": class_id,
                "parentId": parent_id,
                "salesTaxCodeId": sales_tax_code_id,
                "salesOrPurchaseDetails": sales_or_purchase_details,
                "salesAndPurchaseDetails": sales_and_purchase_details,
                "externalId": external_id,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[OtherChargeItem]:
        """Retrieve an other charge item, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the OtherChargeItem.

        Operation ``qbd.otherChargeItems.retrieve``: ``GET /v1/quickbooks-desktop/other-charge-items/{id}``.

        Args:
            id: QuickBooks ID of the other charge item.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.otherChargeItems.retrieve request.
        """
        return self._client._enqueue(
            _QBD_OTHER_CHARGE_ITEMS_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/other-charge-items/" + _pp("id", id),
            cast_to=OtherChargeItem.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def update(
        self,
        id: str,
        *,
        revision_number: str,
        name: str | NotGiven = NOT_GIVEN,
        barcode: BarcodeUpdateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        class_id: str | NotGiven = NOT_GIVEN,
        parent_id: str | NotGiven = NOT_GIVEN,
        sales_tax_code_id: str | NotGiven = NOT_GIVEN,
        sales_or_purchase_details: SalesOrPurchaseDetailUpdateInput | NotGiven = NOT_GIVEN,
        sales_and_purchase_details: SalesAndPurchaseDetailUpdateInput | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[OtherChargeItem]:
        """Update an other charge item, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the OtherChargeItem.

        Operation ``qbd.otherChargeItems.update``: ``POST /v1/quickbooks-desktop/other-charge-items/{id}``.

        Args:
            id: QuickBooks ID of the other charge item.
            revision_number: Current revision of this other charge item. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
            name: Name of this other charge item, unique within its parent level.
            barcode: Barcode details for this other charge item.
            is_active: Whether this other charge item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            class_id: ID of the class for this other charge item.
            parent_id: ID of the parent object, making this other charge item a child in the hierarchy.
            sales_tax_code_id: ID of the sales tax code for this other charge item.
            sales_or_purchase_details: Sales or purchase details details for this other charge item. Cannot be combined with salesAndPurchaseDetails.
            sales_and_purchase_details: Sales and purchase details details for this other charge item. Cannot be combined with salesOrPurchaseDetails.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.otherChargeItems.update request.
        """
        return self._client._enqueue(
            _QBD_OTHER_CHARGE_ITEMS_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/other-charge-items/" + _pp("id", id),
            cast_to=OtherChargeItem.from_wire,
            body={
                "revisionNumber": revision_number,
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "classId": class_id,
                "parentId": parent_id,
                "salesTaxCodeId": sales_tax_code_id,
                "salesOrPurchaseDetails": sales_or_purchase_details,
                "salesAndPurchaseDetails": sales_and_purchase_details,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )


class QbdOtherChargeItemsResource(Resource):
    """Other charge items operations (``client.qbd.other_charge_items``)."""

    @cached_property
    def with_raw_response(self) -> QbdOtherChargeItemsResourceWithRawResponse:
        """The same methods, returning ``RawResponse[T]`` (status code, headers, request ID and ``parse()``)."""
        return QbdOtherChargeItemsResourceWithRawResponse(self)

    @cached_property
    def enqueue(self) -> QbdOtherChargeItemsEnqueue:
        """The async-capable operations in async mode (``Prefer: respond-async``), returning request handles."""
        return QbdOtherChargeItemsEnqueue(self._client)

    def create(
        self,
        *,
        name: str,
        barcode: BarcodeCreateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        class_id: str | NotGiven = NOT_GIVEN,
        parent_id: str | NotGiven = NOT_GIVEN,
        sales_tax_code_id: str | NotGiven = NOT_GIVEN,
        sales_or_purchase_details: SalesOrPurchaseDetailCreateInput | NotGiven = NOT_GIVEN,
        sales_and_purchase_details: SalesAndPurchaseDetailCreateInput | NotGiven = NOT_GIVEN,
        external_id: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> OtherChargeItem:
        """Create an other charge item.

        Creates an other charge item in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second other charge item (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).

        Operation ``qbd.otherChargeItems.create``: ``POST /v1/quickbooks-desktop/other-charge-items``.

        Args:
            name: Name of this other charge item, unique within its parent level.
            barcode: Barcode details for this other charge item.
            is_active: Whether this other charge item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            class_id: ID of the class for this other charge item.
            parent_id: ID of the parent object, making this other charge item a child in the hierarchy.
            sales_tax_code_id: ID of the sales tax code for this other charge item.
            sales_or_purchase_details: Sales or purchase details details for this other charge item. Cannot be combined with salesAndPurchaseDetails.
            sales_and_purchase_details: Sales and purchase details details for this other charge item. Cannot be combined with salesOrPurchaseDetails.
            external_id: Your own UUID for this other charge item, stored by QuickBooks so you can match records with your system.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The OtherChargeItem object.
        """
        return self._client._request(
            _QBD_OTHER_CHARGE_ITEMS_CREATE,
            "POST",
            "/v1/quickbooks-desktop/other-charge-items",
            cast_to=OtherChargeItem.from_wire,
            body={
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "classId": class_id,
                "parentId": parent_id,
                "salesTaxCodeId": sales_tax_code_id,
                "salesOrPurchaseDetails": sales_or_purchase_details,
                "salesAndPurchaseDetails": sales_and_purchase_details,
                "externalId": external_id,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        full_names: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        status: ActiveStatus | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        name_starts_with: str | NotGiven = NOT_GIVEN,
        name_contains: str | NotGiven = NOT_GIVEN,
        name_ends_with: str | NotGiven = NOT_GIVEN,
        name_from: str | NotGiven = NOT_GIVEN,
        name_to: str | NotGiven = NOT_GIVEN,
        class_ids: Sequence[str] | NotGiven = NOT_GIVEN,
        cursor: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> CursorPager[OtherChargeItem]:
        """List other charge items.

        Returns the other charge items that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).

        Operation ``qbd.otherChargeItems.list``: ``GET /v1/quickbooks-desktop/other-charge-items``.

        Iterate to get every item across pages (the next page is requested only when the iteration needs it, or in the background once a page has been held for 2 seconds), or call ``first_page()``, ``iter_pages()`` or ``list_all()``. Raises ``CursorExpiredError`` if QuickBooks drops the iterator; the list is never restarted silently.

        Args:
            ids: Return only the other charge items with these QuickBooks IDs. Cannot be combined with fullNames, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo, classIds. Returns every match in one page (`nextCursor` is null); limit is ignored.
            full_names: Return only the other charge items with these full names (case-insensitive, including parent names separated by colons). Cannot be combined with ids, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo, classIds. Returns every match in one page (`nextCursor` is null); limit is ignored.
            limit: Maximum number of other charge items per page, 1 to 150. Ignored with ids, fullNames, which return every match in one page. Default: ``150``.
            status: Filter other charge items by active state. Defaults to active ones only. Cannot be combined with ids, fullNames.
            updated_after: Return other charge items changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, fullNames.
            updated_before: Return other charge items changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, fullNames.
            name_starts_with: Return other charge items whose name starts with this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_contains: Return other charge items whose name contains this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_ends_with: Return other charge items whose name ends with this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_from: Return other charge items whose name sorts at or after this value. Cannot be combined with ids, fullNames, nameStartsWith, nameContains, nameEndsWith.
            name_to: Return other charge items whose name sorts at or before this value. Cannot be combined with ids, fullNames, nameStartsWith, nameContains, nameEndsWith.
            class_ids: Return only other charge items assigned to these class IDs. Cannot be combined with ids, fullNames.
            cursor: Cursor from the previous page's nextCursor. Send it with no other filters to fetch the next page.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            A pager over OtherChargeItem objects. Nothing is fetched until you iterate.
        """
        return self._client._paginate(
            _QBD_OTHER_CHARGE_ITEMS_LIST,
            "/v1/quickbooks-desktop/other-charge-items",
            query={
                "ids": ids,
                "fullNames": full_names,
                "limit": limit,
                "status": status,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "nameStartsWith": name_starts_with,
                "nameContains": name_contains,
                "nameEndsWith": name_ends_with,
                "nameFrom": name_from,
                "nameTo": name_to,
                "classIds": class_ids,
                "cursor": cursor,
            },
            parse_item=OtherChargeItem.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> OtherChargeItem:
        """Retrieve an other charge item.

        Returns one other charge item by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.

        Operation ``qbd.otherChargeItems.retrieve``: ``GET /v1/quickbooks-desktop/other-charge-items/{id}``.

        Args:
            id: QuickBooks ID of the other charge item.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The OtherChargeItem object.
        """
        return self._client._request(
            _QBD_OTHER_CHARGE_ITEMS_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/other-charge-items/" + _pp("id", id),
            cast_to=OtherChargeItem.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def update(
        self,
        id: str,
        *,
        revision_number: str,
        name: str | NotGiven = NOT_GIVEN,
        barcode: BarcodeUpdateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        class_id: str | NotGiven = NOT_GIVEN,
        parent_id: str | NotGiven = NOT_GIVEN,
        sales_tax_code_id: str | NotGiven = NOT_GIVEN,
        sales_or_purchase_details: SalesOrPurchaseDetailUpdateInput | NotGiven = NOT_GIVEN,
        sales_and_purchase_details: SalesAndPurchaseDetailUpdateInput | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> OtherChargeItem:
        """Update an other charge item.

        Changes the fields you send on an existing other charge item and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the other charge item, reapply your change and send the new revision. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).

        Operation ``qbd.otherChargeItems.update``: ``POST /v1/quickbooks-desktop/other-charge-items/{id}``.

        Args:
            id: QuickBooks ID of the other charge item.
            revision_number: Current revision of this other charge item. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
            name: Name of this other charge item, unique within its parent level.
            barcode: Barcode details for this other charge item.
            is_active: Whether this other charge item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            class_id: ID of the class for this other charge item.
            parent_id: ID of the parent object, making this other charge item a child in the hierarchy.
            sales_tax_code_id: ID of the sales tax code for this other charge item.
            sales_or_purchase_details: Sales or purchase details details for this other charge item. Cannot be combined with salesAndPurchaseDetails.
            sales_and_purchase_details: Sales and purchase details details for this other charge item. Cannot be combined with salesOrPurchaseDetails.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The OtherChargeItem object.
        """
        return self._client._request(
            _QBD_OTHER_CHARGE_ITEMS_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/other-charge-items/" + _pp("id", id),
            cast_to=OtherChargeItem.from_wire,
            body={
                "revisionNumber": revision_number,
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "classId": class_id,
                "parentId": parent_id,
                "salesTaxCodeId": sales_tax_code_id,
                "salesOrPurchaseDetails": sales_or_purchase_details,
                "salesAndPurchaseDetails": sales_and_purchase_details,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )


class AsyncQbdOtherChargeItemsResourceWithRawResponse:
    """``async_client.qbd.other_charge_items.with_raw_response``: the same methods, returning ``RawResponse[T]`` with status, headers and request ID."""

    def __init__(self, resource: AsyncQbdOtherChargeItemsResource) -> None:
        self.create = async_to_raw_response_wrapper(resource.create)
        self.retrieve = async_to_raw_response_wrapper(resource.retrieve)
        self.update = async_to_raw_response_wrapper(resource.update)


class AsyncQbdOtherChargeItemsEnqueue(AsyncResource):
    """``async_client.qbd.other_charge_items.enqueue``: the async-capable operations in async mode, returning request handles."""

    async def create(
        self,
        *,
        name: str,
        barcode: BarcodeCreateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        class_id: str | NotGiven = NOT_GIVEN,
        parent_id: str | NotGiven = NOT_GIVEN,
        sales_tax_code_id: str | NotGiven = NOT_GIVEN,
        sales_or_purchase_details: SalesOrPurchaseDetailCreateInput | NotGiven = NOT_GIVEN,
        sales_and_purchase_details: SalesAndPurchaseDetailCreateInput | NotGiven = NOT_GIVEN,
        external_id: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[OtherChargeItem]:
        """Create an other charge item, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the OtherChargeItem.

        Operation ``qbd.otherChargeItems.create``: ``POST /v1/quickbooks-desktop/other-charge-items``.

        Args:
            name: Name of this other charge item, unique within its parent level.
            barcode: Barcode details for this other charge item.
            is_active: Whether this other charge item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            class_id: ID of the class for this other charge item.
            parent_id: ID of the parent object, making this other charge item a child in the hierarchy.
            sales_tax_code_id: ID of the sales tax code for this other charge item.
            sales_or_purchase_details: Sales or purchase details details for this other charge item. Cannot be combined with salesAndPurchaseDetails.
            sales_and_purchase_details: Sales and purchase details details for this other charge item. Cannot be combined with salesOrPurchaseDetails.
            external_id: Your own UUID for this other charge item, stored by QuickBooks so you can match records with your system.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.otherChargeItems.create request.
        """
        return await self._client._enqueue(
            _QBD_OTHER_CHARGE_ITEMS_CREATE,
            "POST",
            "/v1/quickbooks-desktop/other-charge-items",
            cast_to=OtherChargeItem.from_wire,
            body={
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "classId": class_id,
                "parentId": parent_id,
                "salesTaxCodeId": sales_tax_code_id,
                "salesOrPurchaseDetails": sales_or_purchase_details,
                "salesAndPurchaseDetails": sales_and_purchase_details,
                "externalId": external_id,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[OtherChargeItem]:
        """Retrieve an other charge item, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the OtherChargeItem.

        Operation ``qbd.otherChargeItems.retrieve``: ``GET /v1/quickbooks-desktop/other-charge-items/{id}``.

        Args:
            id: QuickBooks ID of the other charge item.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.otherChargeItems.retrieve request.
        """
        return await self._client._enqueue(
            _QBD_OTHER_CHARGE_ITEMS_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/other-charge-items/" + _pp("id", id),
            cast_to=OtherChargeItem.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def update(
        self,
        id: str,
        *,
        revision_number: str,
        name: str | NotGiven = NOT_GIVEN,
        barcode: BarcodeUpdateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        class_id: str | NotGiven = NOT_GIVEN,
        parent_id: str | NotGiven = NOT_GIVEN,
        sales_tax_code_id: str | NotGiven = NOT_GIVEN,
        sales_or_purchase_details: SalesOrPurchaseDetailUpdateInput | NotGiven = NOT_GIVEN,
        sales_and_purchase_details: SalesAndPurchaseDetailUpdateInput | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[OtherChargeItem]:
        """Update an other charge item, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the OtherChargeItem.

        Operation ``qbd.otherChargeItems.update``: ``POST /v1/quickbooks-desktop/other-charge-items/{id}``.

        Args:
            id: QuickBooks ID of the other charge item.
            revision_number: Current revision of this other charge item. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
            name: Name of this other charge item, unique within its parent level.
            barcode: Barcode details for this other charge item.
            is_active: Whether this other charge item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            class_id: ID of the class for this other charge item.
            parent_id: ID of the parent object, making this other charge item a child in the hierarchy.
            sales_tax_code_id: ID of the sales tax code for this other charge item.
            sales_or_purchase_details: Sales or purchase details details for this other charge item. Cannot be combined with salesAndPurchaseDetails.
            sales_and_purchase_details: Sales and purchase details details for this other charge item. Cannot be combined with salesOrPurchaseDetails.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.otherChargeItems.update request.
        """
        return await self._client._enqueue(
            _QBD_OTHER_CHARGE_ITEMS_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/other-charge-items/" + _pp("id", id),
            cast_to=OtherChargeItem.from_wire,
            body={
                "revisionNumber": revision_number,
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "classId": class_id,
                "parentId": parent_id,
                "salesTaxCodeId": sales_tax_code_id,
                "salesOrPurchaseDetails": sales_or_purchase_details,
                "salesAndPurchaseDetails": sales_and_purchase_details,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )


class AsyncQbdOtherChargeItemsResource(AsyncResource):
    """Other charge items operations (``client.qbd.other_charge_items``)."""

    @cached_property
    def with_raw_response(self) -> AsyncQbdOtherChargeItemsResourceWithRawResponse:
        """The same methods, returning ``RawResponse[T]`` (status code, headers, request ID and ``parse()``)."""
        return AsyncQbdOtherChargeItemsResourceWithRawResponse(self)

    @cached_property
    def enqueue(self) -> AsyncQbdOtherChargeItemsEnqueue:
        """The async-capable operations in async mode (``Prefer: respond-async``), returning request handles."""
        return AsyncQbdOtherChargeItemsEnqueue(self._client)

    async def create(
        self,
        *,
        name: str,
        barcode: BarcodeCreateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        class_id: str | NotGiven = NOT_GIVEN,
        parent_id: str | NotGiven = NOT_GIVEN,
        sales_tax_code_id: str | NotGiven = NOT_GIVEN,
        sales_or_purchase_details: SalesOrPurchaseDetailCreateInput | NotGiven = NOT_GIVEN,
        sales_and_purchase_details: SalesAndPurchaseDetailCreateInput | NotGiven = NOT_GIVEN,
        external_id: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> OtherChargeItem:
        """Create an other charge item.

        Creates an other charge item in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second other charge item (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).

        Operation ``qbd.otherChargeItems.create``: ``POST /v1/quickbooks-desktop/other-charge-items``.

        Args:
            name: Name of this other charge item, unique within its parent level.
            barcode: Barcode details for this other charge item.
            is_active: Whether this other charge item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            class_id: ID of the class for this other charge item.
            parent_id: ID of the parent object, making this other charge item a child in the hierarchy.
            sales_tax_code_id: ID of the sales tax code for this other charge item.
            sales_or_purchase_details: Sales or purchase details details for this other charge item. Cannot be combined with salesAndPurchaseDetails.
            sales_and_purchase_details: Sales and purchase details details for this other charge item. Cannot be combined with salesOrPurchaseDetails.
            external_id: Your own UUID for this other charge item, stored by QuickBooks so you can match records with your system.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The OtherChargeItem object.
        """
        return await self._client._request(
            _QBD_OTHER_CHARGE_ITEMS_CREATE,
            "POST",
            "/v1/quickbooks-desktop/other-charge-items",
            cast_to=OtherChargeItem.from_wire,
            body={
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "classId": class_id,
                "parentId": parent_id,
                "salesTaxCodeId": sales_tax_code_id,
                "salesOrPurchaseDetails": sales_or_purchase_details,
                "salesAndPurchaseDetails": sales_and_purchase_details,
                "externalId": external_id,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        full_names: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        status: ActiveStatus | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        name_starts_with: str | NotGiven = NOT_GIVEN,
        name_contains: str | NotGiven = NOT_GIVEN,
        name_ends_with: str | NotGiven = NOT_GIVEN,
        name_from: str | NotGiven = NOT_GIVEN,
        name_to: str | NotGiven = NOT_GIVEN,
        class_ids: Sequence[str] | NotGiven = NOT_GIVEN,
        cursor: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> AsyncCursorPager[OtherChargeItem]:
        """List other charge items.

        Returns the other charge items that match your filters. Results are paged: pass `nextCursor` as `cursor` until `hasMore` is false. A cursor lives only inside the current QuickBooks session, so request the next page promptly; an expired cursor returns `410 CURSOR_EXPIRED`. See [Pagination](https://www.desktopaccountingapi.com/docs/guides/pagination/).

        Operation ``qbd.otherChargeItems.list``: ``GET /v1/quickbooks-desktop/other-charge-items``.

        Iterate with ``async for`` to get every item across pages (the next page is requested only when the iteration needs it, or in the background once a page has been held for 2 seconds), or call ``first_page()``, ``iter_pages()`` or ``list_all()``. Raises ``CursorExpiredError`` if QuickBooks drops the iterator; the list is never restarted silently.

        Args:
            ids: Return only the other charge items with these QuickBooks IDs. Cannot be combined with fullNames, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo, classIds. Returns every match in one page (`nextCursor` is null); limit is ignored.
            full_names: Return only the other charge items with these full names (case-insensitive, including parent names separated by colons). Cannot be combined with ids, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo, classIds. Returns every match in one page (`nextCursor` is null); limit is ignored.
            limit: Maximum number of other charge items per page, 1 to 150. Ignored with ids, fullNames, which return every match in one page. Default: ``150``.
            status: Filter other charge items by active state. Defaults to active ones only. Cannot be combined with ids, fullNames.
            updated_after: Return other charge items changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, fullNames.
            updated_before: Return other charge items changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, fullNames.
            name_starts_with: Return other charge items whose name starts with this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_contains: Return other charge items whose name contains this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_ends_with: Return other charge items whose name ends with this text (case-insensitive). Cannot be combined with ids, fullNames, nameFrom, nameTo.
            name_from: Return other charge items whose name sorts at or after this value. Cannot be combined with ids, fullNames, nameStartsWith, nameContains, nameEndsWith.
            name_to: Return other charge items whose name sorts at or before this value. Cannot be combined with ids, fullNames, nameStartsWith, nameContains, nameEndsWith.
            class_ids: Return only other charge items assigned to these class IDs. Cannot be combined with ids, fullNames.
            cursor: Cursor from the previous page's nextCursor. Send it with no other filters to fetch the next page.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            A pager over OtherChargeItem objects. Nothing is fetched until you iterate.
        """
        return self._client._paginate(
            _QBD_OTHER_CHARGE_ITEMS_LIST,
            "/v1/quickbooks-desktop/other-charge-items",
            query={
                "ids": ids,
                "fullNames": full_names,
                "limit": limit,
                "status": status,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "nameStartsWith": name_starts_with,
                "nameContains": name_contains,
                "nameEndsWith": name_ends_with,
                "nameFrom": name_from,
                "nameTo": name_to,
                "classIds": class_ids,
                "cursor": cursor,
            },
            parse_item=OtherChargeItem.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> OtherChargeItem:
        """Retrieve an other charge item.

        Returns one other charge item by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.

        Operation ``qbd.otherChargeItems.retrieve``: ``GET /v1/quickbooks-desktop/other-charge-items/{id}``.

        Args:
            id: QuickBooks ID of the other charge item.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The OtherChargeItem object.
        """
        return await self._client._request(
            _QBD_OTHER_CHARGE_ITEMS_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/other-charge-items/" + _pp("id", id),
            cast_to=OtherChargeItem.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def update(
        self,
        id: str,
        *,
        revision_number: str,
        name: str | NotGiven = NOT_GIVEN,
        barcode: BarcodeUpdateInput | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        class_id: str | NotGiven = NOT_GIVEN,
        parent_id: str | NotGiven = NOT_GIVEN,
        sales_tax_code_id: str | NotGiven = NOT_GIVEN,
        sales_or_purchase_details: SalesOrPurchaseDetailUpdateInput | NotGiven = NOT_GIVEN,
        sales_and_purchase_details: SalesAndPurchaseDetailUpdateInput | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> OtherChargeItem:
        """Update an other charge item.

        Changes the fields you send on an existing other charge item and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the other charge item, reapply your change and send the new revision. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).

        Operation ``qbd.otherChargeItems.update``: ``POST /v1/quickbooks-desktop/other-charge-items/{id}``.

        Args:
            id: QuickBooks ID of the other charge item.
            revision_number: Current revision of this other charge item. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
            name: Name of this other charge item, unique within its parent level.
            barcode: Barcode details for this other charge item.
            is_active: Whether this other charge item is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            class_id: ID of the class for this other charge item.
            parent_id: ID of the parent object, making this other charge item a child in the hierarchy.
            sales_tax_code_id: ID of the sales tax code for this other charge item.
            sales_or_purchase_details: Sales or purchase details details for this other charge item. Cannot be combined with salesAndPurchaseDetails.
            sales_and_purchase_details: Sales and purchase details details for this other charge item. Cannot be combined with salesOrPurchaseDetails.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The OtherChargeItem object.
        """
        return await self._client._request(
            _QBD_OTHER_CHARGE_ITEMS_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/other-charge-items/" + _pp("id", id),
            cast_to=OtherChargeItem.from_wire,
            body={
                "revisionNumber": revision_number,
                "name": name,
                "barcode": barcode,
                "isActive": is_active,
                "classId": class_id,
                "parentId": parent_id,
                "salesTaxCodeId": sales_tax_code_id,
                "salesOrPurchaseDetails": sales_or_purchase_details,
                "salesAndPurchaseDetails": sales_and_purchase_details,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )
