# Code generated by packages/sdk-generator. DO NOT EDIT.
# Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:d4adaec794b6cf028d0f87bcaed3668ec305d5e364a02008e8a22258ee3a7d59
"""Sales tax codes operations (``client.qbd.sales_tax_codes``)."""

from __future__ import annotations

from collections.abc import Sequence
from functools import cached_property

from ..._base_client import Op
from ..._handles import AsyncRequestHandle, RequestHandle
from ..._resource import AsyncResource, Resource
from ..._response import async_to_raw_response_wrapper, to_raw_response_wrapper
from ..._types import NOT_GIVEN, NotGiven
from ..._wire import DateOrDateTime
from ..._wire import path_param as _pp
from ...types import ActiveStatus, SalesTaxCode, SalesTaxCodeList

_QBD_SALES_TAX_CODES_CREATE = Op(
    "qbd.salesTaxCodes.create",
    write=True,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_SALES_TAX_CODES_LIST = Op(
    "qbd.salesTaxCodes.list",
    write=False,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_SALES_TAX_CODES_RETRIEVE = Op(
    "qbd.salesTaxCodes.retrieve",
    write=False,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)
_QBD_SALES_TAX_CODES_UPDATE = Op(
    "qbd.salesTaxCodes.update",
    write=True,
    end_user=True,
    server_timeout=True,
    queue_ttl=True,
)


class QbdSalesTaxCodesResourceWithRawResponse:
    """``client.qbd.sales_tax_codes.with_raw_response``: the same methods, returning ``RawResponse[T]`` with status, headers and request ID."""

    def __init__(self, resource: QbdSalesTaxCodesResource) -> None:
        self.create = to_raw_response_wrapper(resource.create)
        self.list = to_raw_response_wrapper(resource.list)
        self.retrieve = to_raw_response_wrapper(resource.retrieve)
        self.update = to_raw_response_wrapper(resource.update)


class QbdSalesTaxCodesEnqueue(Resource):
    """``client.qbd.sales_tax_codes.enqueue``: the async-capable operations in async mode, returning request handles."""

    def create(
        self,
        *,
        name: str,
        is_taxable: bool,
        is_active: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[SalesTaxCode]:
        """Create a sales tax code, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the SalesTaxCode.

        Operation ``qbd.salesTaxCodes.create``: ``POST /v1/quickbooks-desktop/sales-tax-codes``.

        Args:
            name: Name of this sales tax code, unique within its parent level.
            is_taxable: Whether this sales tax code is taxable.
            is_active: Whether this sales tax code is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            description: Description of this sales tax code.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.salesTaxCodes.create request.
        """
        return self._client._enqueue(
            _QBD_SALES_TAX_CODES_CREATE,
            "POST",
            "/v1/quickbooks-desktop/sales-tax-codes",
            cast_to=SalesTaxCode.from_wire,
            body={
                "name": name,
                "isTaxable": is_taxable,
                "isActive": is_active,
                "description": description,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        names: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        status: ActiveStatus | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        name_starts_with: str | NotGiven = NOT_GIVEN,
        name_contains: str | NotGiven = NOT_GIVEN,
        name_ends_with: str | NotGiven = NOT_GIVEN,
        name_from: str | NotGiven = NOT_GIVEN,
        name_to: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[SalesTaxCodeList]:
        """List sales tax codes, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the SalesTaxCodeList.

        Operation ``qbd.salesTaxCodes.list``: ``GET /v1/quickbooks-desktop/sales-tax-codes``.

        Args:
            ids: Return only the sales tax codes with these QuickBooks IDs. Cannot be combined with names, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            names: Return only the sales tax codes with these names (case-insensitive). Cannot be combined with ids, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            limit: Maximum number of sales tax codes to return. Cannot be combined with ids, names.
            status: Filter sales tax codes by active state. Defaults to active ones only. Cannot be combined with ids, names.
            updated_after: Return sales tax codes changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
            updated_before: Return sales tax codes changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
            name_starts_with: Return sales tax codes whose name starts with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_contains: Return sales tax codes whose name contains this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_ends_with: Return sales tax codes whose name ends with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_from: Return sales tax codes whose name sorts at or after this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
            name_to: Return sales tax codes whose name sorts at or before this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.salesTaxCodes.list request.
        """
        return self._client._enqueue(
            _QBD_SALES_TAX_CODES_LIST,
            "GET",
            "/v1/quickbooks-desktop/sales-tax-codes",
            cast_to=SalesTaxCodeList.from_wire,
            query={
                "ids": ids,
                "names": names,
                "limit": limit,
                "status": status,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "nameStartsWith": name_starts_with,
                "nameContains": name_contains,
                "nameEndsWith": name_ends_with,
                "nameFrom": name_from,
                "nameTo": name_to,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[SalesTaxCode]:
        """Retrieve a sales tax code, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the SalesTaxCode.

        Operation ``qbd.salesTaxCodes.retrieve``: ``GET /v1/quickbooks-desktop/sales-tax-codes/{id}``.

        Args:
            id: QuickBooks ID of the sales tax code.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.salesTaxCodes.retrieve request.
        """
        return self._client._enqueue(
            _QBD_SALES_TAX_CODES_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/sales-tax-codes/" + _pp("id", id),
            cast_to=SalesTaxCode.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    def update(
        self,
        id: str,
        *,
        revision_number: str,
        name: str | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        is_taxable: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven | None = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> RequestHandle[SalesTaxCode]:
        """Update a sales tax code, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``handle.wait()`` long-polls until QuickBooks has processed it and returns the SalesTaxCode.

        Operation ``qbd.salesTaxCodes.update``: ``POST /v1/quickbooks-desktop/sales-tax-codes/{id}``.

        Args:
            id: QuickBooks ID of the sales tax code.
            revision_number: Current revision of this sales tax code. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
            name: Name of this sales tax code, unique within its parent level.
            is_active: Whether this sales tax code is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            is_taxable: Whether this sales tax code is taxable.
            description: Description of this sales tax code. Pass ``None`` to clear it.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.salesTaxCodes.update request.
        """
        return self._client._enqueue(
            _QBD_SALES_TAX_CODES_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/sales-tax-codes/" + _pp("id", id),
            cast_to=SalesTaxCode.from_wire,
            body={
                "revisionNumber": revision_number,
                "name": name,
                "isActive": is_active,
                "isTaxable": is_taxable,
                "description": description,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )


class QbdSalesTaxCodesResource(Resource):
    """Sales tax codes operations (``client.qbd.sales_tax_codes``)."""

    @cached_property
    def with_raw_response(self) -> QbdSalesTaxCodesResourceWithRawResponse:
        """The same methods, returning ``RawResponse[T]`` (status code, headers, request ID and ``parse()``)."""
        return QbdSalesTaxCodesResourceWithRawResponse(self)

    @cached_property
    def enqueue(self) -> QbdSalesTaxCodesEnqueue:
        """The async-capable operations in async mode (``Prefer: respond-async``), returning request handles."""
        return QbdSalesTaxCodesEnqueue(self._client)

    def create(
        self,
        *,
        name: str,
        is_taxable: bool,
        is_active: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> SalesTaxCode:
        """Create a sales tax code.

        Creates a sales tax code in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second sales tax code (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).

        Operation ``qbd.salesTaxCodes.create``: ``POST /v1/quickbooks-desktop/sales-tax-codes``.

        Args:
            name: Name of this sales tax code, unique within its parent level.
            is_taxable: Whether this sales tax code is taxable.
            is_active: Whether this sales tax code is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            description: Description of this sales tax code.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The SalesTaxCode object.
        """
        return self._client._request(
            _QBD_SALES_TAX_CODES_CREATE,
            "POST",
            "/v1/quickbooks-desktop/sales-tax-codes",
            cast_to=SalesTaxCode.from_wire,
            body={
                "name": name,
                "isTaxable": is_taxable,
                "isActive": is_active,
                "description": description,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        names: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        status: ActiveStatus | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        name_starts_with: str | NotGiven = NOT_GIVEN,
        name_contains: str | NotGiven = NOT_GIVEN,
        name_ends_with: str | NotGiven = NOT_GIVEN,
        name_from: str | NotGiven = NOT_GIVEN,
        name_to: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> SalesTaxCodeList:
        """List sales tax codes.

        Returns the sales tax codes that match your filters. QuickBooks has no cursor for this list, so the response contains every matching sales tax code at once.

        Operation ``qbd.salesTaxCodes.list``: ``GET /v1/quickbooks-desktop/sales-tax-codes``.

        Args:
            ids: Return only the sales tax codes with these QuickBooks IDs. Cannot be combined with names, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            names: Return only the sales tax codes with these names (case-insensitive). Cannot be combined with ids, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            limit: Maximum number of sales tax codes to return. Cannot be combined with ids, names.
            status: Filter sales tax codes by active state. Defaults to active ones only. Cannot be combined with ids, names.
            updated_after: Return sales tax codes changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
            updated_before: Return sales tax codes changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
            name_starts_with: Return sales tax codes whose name starts with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_contains: Return sales tax codes whose name contains this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_ends_with: Return sales tax codes whose name ends with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_from: Return sales tax codes whose name sorts at or after this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
            name_to: Return sales tax codes whose name sorts at or before this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The SalesTaxCodeList object.
        """
        return self._client._request(
            _QBD_SALES_TAX_CODES_LIST,
            "GET",
            "/v1/quickbooks-desktop/sales-tax-codes",
            cast_to=SalesTaxCodeList.from_wire,
            query={
                "ids": ids,
                "names": names,
                "limit": limit,
                "status": status,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "nameStartsWith": name_starts_with,
                "nameContains": name_contains,
                "nameEndsWith": name_ends_with,
                "nameFrom": name_from,
                "nameTo": name_to,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> SalesTaxCode:
        """Retrieve a sales tax code.

        Returns one sales tax code by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.

        Operation ``qbd.salesTaxCodes.retrieve``: ``GET /v1/quickbooks-desktop/sales-tax-codes/{id}``.

        Args:
            id: QuickBooks ID of the sales tax code.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The SalesTaxCode object.
        """
        return self._client._request(
            _QBD_SALES_TAX_CODES_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/sales-tax-codes/" + _pp("id", id),
            cast_to=SalesTaxCode.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    def update(
        self,
        id: str,
        *,
        revision_number: str,
        name: str | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        is_taxable: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven | None = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> SalesTaxCode:
        """Update a sales tax code.

        Changes the fields you send on an existing sales tax code and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the sales tax code, reapply your change and send the new revision. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).

        Operation ``qbd.salesTaxCodes.update``: ``POST /v1/quickbooks-desktop/sales-tax-codes/{id}``.

        Args:
            id: QuickBooks ID of the sales tax code.
            revision_number: Current revision of this sales tax code. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
            name: Name of this sales tax code, unique within its parent level.
            is_active: Whether this sales tax code is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            is_taxable: Whether this sales tax code is taxable.
            description: Description of this sales tax code. Pass ``None`` to clear it.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The SalesTaxCode object.
        """
        return self._client._request(
            _QBD_SALES_TAX_CODES_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/sales-tax-codes/" + _pp("id", id),
            cast_to=SalesTaxCode.from_wire,
            body={
                "revisionNumber": revision_number,
                "name": name,
                "isActive": is_active,
                "isTaxable": is_taxable,
                "description": description,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )


class AsyncQbdSalesTaxCodesResourceWithRawResponse:
    """``async_client.qbd.sales_tax_codes.with_raw_response``: the same methods, returning ``RawResponse[T]`` with status, headers and request ID."""

    def __init__(self, resource: AsyncQbdSalesTaxCodesResource) -> None:
        self.create = async_to_raw_response_wrapper(resource.create)
        self.list = async_to_raw_response_wrapper(resource.list)
        self.retrieve = async_to_raw_response_wrapper(resource.retrieve)
        self.update = async_to_raw_response_wrapper(resource.update)


class AsyncQbdSalesTaxCodesEnqueue(AsyncResource):
    """``async_client.qbd.sales_tax_codes.enqueue``: the async-capable operations in async mode, returning request handles."""

    async def create(
        self,
        *,
        name: str,
        is_taxable: bool,
        is_active: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[SalesTaxCode]:
        """Create a sales tax code, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the SalesTaxCode.

        Operation ``qbd.salesTaxCodes.create``: ``POST /v1/quickbooks-desktop/sales-tax-codes``.

        Args:
            name: Name of this sales tax code, unique within its parent level.
            is_taxable: Whether this sales tax code is taxable.
            is_active: Whether this sales tax code is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            description: Description of this sales tax code.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.salesTaxCodes.create request.
        """
        return await self._client._enqueue(
            _QBD_SALES_TAX_CODES_CREATE,
            "POST",
            "/v1/quickbooks-desktop/sales-tax-codes",
            cast_to=SalesTaxCode.from_wire,
            body={
                "name": name,
                "isTaxable": is_taxable,
                "isActive": is_active,
                "description": description,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        names: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        status: ActiveStatus | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        name_starts_with: str | NotGiven = NOT_GIVEN,
        name_contains: str | NotGiven = NOT_GIVEN,
        name_ends_with: str | NotGiven = NOT_GIVEN,
        name_from: str | NotGiven = NOT_GIVEN,
        name_to: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[SalesTaxCodeList]:
        """List sales tax codes, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the SalesTaxCodeList.

        Operation ``qbd.salesTaxCodes.list``: ``GET /v1/quickbooks-desktop/sales-tax-codes``.

        Args:
            ids: Return only the sales tax codes with these QuickBooks IDs. Cannot be combined with names, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            names: Return only the sales tax codes with these names (case-insensitive). Cannot be combined with ids, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            limit: Maximum number of sales tax codes to return. Cannot be combined with ids, names.
            status: Filter sales tax codes by active state. Defaults to active ones only. Cannot be combined with ids, names.
            updated_after: Return sales tax codes changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
            updated_before: Return sales tax codes changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
            name_starts_with: Return sales tax codes whose name starts with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_contains: Return sales tax codes whose name contains this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_ends_with: Return sales tax codes whose name ends with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_from: Return sales tax codes whose name sorts at or after this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
            name_to: Return sales tax codes whose name sorts at or before this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.salesTaxCodes.list request.
        """
        return await self._client._enqueue(
            _QBD_SALES_TAX_CODES_LIST,
            "GET",
            "/v1/quickbooks-desktop/sales-tax-codes",
            cast_to=SalesTaxCodeList.from_wire,
            query={
                "ids": ids,
                "names": names,
                "limit": limit,
                "status": status,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "nameStartsWith": name_starts_with,
                "nameContains": name_contains,
                "nameEndsWith": name_ends_with,
                "nameFrom": name_from,
                "nameTo": name_to,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[SalesTaxCode]:
        """Retrieve a sales tax code, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the SalesTaxCode.

        Operation ``qbd.salesTaxCodes.retrieve``: ``GET /v1/quickbooks-desktop/sales-tax-codes/{id}``.

        Args:
            id: QuickBooks ID of the sales tax code.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.salesTaxCodes.retrieve request.
        """
        return await self._client._enqueue(
            _QBD_SALES_TAX_CODES_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/sales-tax-codes/" + _pp("id", id),
            cast_to=SalesTaxCode.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )

    async def update(
        self,
        id: str,
        *,
        revision_number: str,
        name: str | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        is_taxable: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven | None = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        queue_ttl: int | None = None,
    ) -> AsyncRequestHandle[SalesTaxCode]:
        """Update a sales tax code, in async mode (``Prefer: respond-async``).

        Returns as soon as the request is queued. ``await handle.wait()`` long-polls until QuickBooks has processed it and returns the SalesTaxCode.

        Operation ``qbd.salesTaxCodes.update``: ``POST /v1/quickbooks-desktop/sales-tax-codes/{id}``.

        Args:
            id: QuickBooks ID of the sales tax code.
            revision_number: Current revision of this sales tax code. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
            name: Name of this sales tax code, unique within its parent level.
            is_active: Whether this sales tax code is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            is_taxable: Whether this sales tax code is taxable.
            description: Description of this sales tax code. Pass ``None`` to clear it.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            queue_ttl: Latest time in seconds the queued request may still be sent to QuickBooks (``Daapi-Queue-Ttl-Seconds``, 10-86400). Defaults to the API default (3600).

        Returns:
            A request handle for the queued qbd.salesTaxCodes.update request.
        """
        return await self._client._enqueue(
            _QBD_SALES_TAX_CODES_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/sales-tax-codes/" + _pp("id", id),
            cast_to=SalesTaxCode.from_wire,
            body={
                "revisionNumber": revision_number,
                "name": name,
                "isActive": is_active,
                "isTaxable": is_taxable,
                "description": description,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            queue_ttl=queue_ttl,
        )


class AsyncQbdSalesTaxCodesResource(AsyncResource):
    """Sales tax codes operations (``client.qbd.sales_tax_codes``)."""

    @cached_property
    def with_raw_response(self) -> AsyncQbdSalesTaxCodesResourceWithRawResponse:
        """The same methods, returning ``RawResponse[T]`` (status code, headers, request ID and ``parse()``)."""
        return AsyncQbdSalesTaxCodesResourceWithRawResponse(self)

    @cached_property
    def enqueue(self) -> AsyncQbdSalesTaxCodesEnqueue:
        """The async-capable operations in async mode (``Prefer: respond-async``), returning request handles."""
        return AsyncQbdSalesTaxCodesEnqueue(self._client)

    async def create(
        self,
        *,
        name: str,
        is_taxable: bool,
        is_active: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> SalesTaxCode:
        """Create a sales tax code.

        Creates a sales tax code in QuickBooks Desktop and returns it. Send an `Idempotency-Key` header so a retry after a network error never creates a second sales tax code (the SDKs do this for you). See [Idempotency and safe retries](https://www.desktopaccountingapi.com/docs/guides/idempotency/).

        Operation ``qbd.salesTaxCodes.create``: ``POST /v1/quickbooks-desktop/sales-tax-codes``.

        Args:
            name: Name of this sales tax code, unique within its parent level.
            is_taxable: Whether this sales tax code is taxable.
            is_active: Whether this sales tax code is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            description: Description of this sales tax code.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The SalesTaxCode object.
        """
        return await self._client._request(
            _QBD_SALES_TAX_CODES_CREATE,
            "POST",
            "/v1/quickbooks-desktop/sales-tax-codes",
            cast_to=SalesTaxCode.from_wire,
            body={
                "name": name,
                "isTaxable": is_taxable,
                "isActive": is_active,
                "description": description,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def list(
        self,
        *,
        ids: Sequence[str] | NotGiven = NOT_GIVEN,
        names: Sequence[str] | NotGiven = NOT_GIVEN,
        limit: int | NotGiven = NOT_GIVEN,
        status: ActiveStatus | NotGiven = NOT_GIVEN,
        updated_after: DateOrDateTime | NotGiven = NOT_GIVEN,
        updated_before: DateOrDateTime | NotGiven = NOT_GIVEN,
        name_starts_with: str | NotGiven = NOT_GIVEN,
        name_contains: str | NotGiven = NOT_GIVEN,
        name_ends_with: str | NotGiven = NOT_GIVEN,
        name_from: str | NotGiven = NOT_GIVEN,
        name_to: str | NotGiven = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> SalesTaxCodeList:
        """List sales tax codes.

        Returns the sales tax codes that match your filters. QuickBooks has no cursor for this list, so the response contains every matching sales tax code at once.

        Operation ``qbd.salesTaxCodes.list``: ``GET /v1/quickbooks-desktop/sales-tax-codes``.

        Args:
            ids: Return only the sales tax codes with these QuickBooks IDs. Cannot be combined with names, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            names: Return only the sales tax codes with these names (case-insensitive). Cannot be combined with ids, limit, status, updatedAfter, updatedBefore, nameStartsWith, nameContains, nameEndsWith, nameFrom, nameTo.
            limit: Maximum number of sales tax codes to return. Cannot be combined with ids, names.
            status: Filter sales tax codes by active state. Defaults to active ones only. Cannot be combined with ids, names.
            updated_after: Return sales tax codes changed on or after this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
            updated_before: Return sales tax codes changed on or before this date or date-time (QuickBooks local time unless an offset is given). Cannot be combined with ids, names.
            name_starts_with: Return sales tax codes whose name starts with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_contains: Return sales tax codes whose name contains this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_ends_with: Return sales tax codes whose name ends with this text (case-insensitive). Cannot be combined with ids, names, nameFrom, nameTo.
            name_from: Return sales tax codes whose name sorts at or after this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
            name_to: Return sales tax codes whose name sorts at or before this value. Cannot be combined with ids, names, nameStartsWith, nameContains, nameEndsWith.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The SalesTaxCodeList object.
        """
        return await self._client._request(
            _QBD_SALES_TAX_CODES_LIST,
            "GET",
            "/v1/quickbooks-desktop/sales-tax-codes",
            cast_to=SalesTaxCodeList.from_wire,
            query={
                "ids": ids,
                "names": names,
                "limit": limit,
                "status": status,
                "updatedAfter": updated_after,
                "updatedBefore": updated_before,
                "nameStartsWith": name_starts_with,
                "nameContains": name_contains,
                "nameEndsWith": name_ends_with,
                "nameFrom": name_from,
                "nameTo": name_to,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def retrieve(
        self,
        id: str,
        *,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> SalesTaxCode:
        """Retrieve a sales tax code.

        Returns one sales tax code by its QuickBooks ID. An unknown ID returns `404 QBD_OBJECT_NOT_FOUND`.

        Operation ``qbd.salesTaxCodes.retrieve``: ``GET /v1/quickbooks-desktop/sales-tax-codes/{id}``.

        Args:
            id: QuickBooks ID of the sales tax code.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The SalesTaxCode object.
        """
        return await self._client._request(
            _QBD_SALES_TAX_CODES_RETRIEVE,
            "GET",
            "/v1/quickbooks-desktop/sales-tax-codes/" + _pp("id", id),
            cast_to=SalesTaxCode.from_wire,
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )

    async def update(
        self,
        id: str,
        *,
        revision_number: str,
        name: str | NotGiven = NOT_GIVEN,
        is_active: bool | NotGiven = NOT_GIVEN,
        is_taxable: bool | NotGiven = NOT_GIVEN,
        description: str | NotGiven | None = NOT_GIVEN,
        end_user_id: str | None = None,
        conductor_end_user_id: str | None = None,
        idempotency_key: str | None = None,
        timeout: float | None = None,
        total_timeout: float | None = None,
        max_retries: int | None = None,
        server_timeout: int | None = None,
    ) -> SalesTaxCode:
        """Update a sales tax code.

        Changes the fields you send on an existing sales tax code and leaves omitted fields unchanged. Requires the current `revisionNumber`. A stale `revisionNumber` returns `409 QBD_REVISION_NUMBER_STALE`: retrieve the sales tax code, reapply your change and send the new revision. See [Updates and line items](https://www.desktopaccountingapi.com/docs/quickbooks/updates-and-line-items/).

        Operation ``qbd.salesTaxCodes.update``: ``POST /v1/quickbooks-desktop/sales-tax-codes/{id}``.

        Args:
            id: QuickBooks ID of the sales tax code.
            revision_number: Current revision of this sales tax code. Send it unchanged when updating; a stale value is rejected. QuickBooks changes it at most once per second, so a second edit within the same second keeps the same value. This API spaces its own consecutive writes to one object by over a second; edits made elsewhere in the same second are not detected.
            name: Name of this sales tax code, unique within its parent level.
            is_active: Whether this sales tax code is active. Inactive objects stay in QuickBooks but are hidden from most lists.
            is_taxable: Whether this sales tax code is taxable.
            description: Description of this sales tax code. Pass ``None`` to clear it.
            end_user_id: End user (``eu_...``) whose QuickBooks company file to use. Defaults to the client's ``end_user_id``.
            conductor_end_user_id: Alias of ``end_user_id`` with Conductor's name, for code ported from ``conductor-py``. Passing both with different values raises ``DaapiError``.
            idempotency_key: Makes the write safe to retry (``Idempotency-Key``). Defaults to a new UUID that is reused on every retry of this call.
            timeout: Client-side timeout in seconds for each HTTP attempt; also the time budget for waiting on a request that is still running in QuickBooks. Defaults to the client's ``timeout``.
            total_timeout: Time budget in seconds for the whole call: every attempt, retry backoff and the wait for a pending request. Defaults to the client's ``total_timeout`` (none).
            max_retries: Retries for network errors, 429 and retryable 5xx responses. Defaults to the client's ``max_retries``.
            server_timeout: Seconds the API waits for QuickBooks before answering (``Daapi-Timeout-Seconds``, 1-300). Defaults to the client's ``server_timeout`` or the API default.

        Returns:
            The SalesTaxCode object.
        """
        return await self._client._request(
            _QBD_SALES_TAX_CODES_UPDATE,
            "POST",
            "/v1/quickbooks-desktop/sales-tax-codes/" + _pp("id", id),
            cast_to=SalesTaxCode.from_wire,
            body={
                "revisionNumber": revision_number,
                "name": name,
                "isActive": is_active,
                "isTaxable": is_taxable,
                "description": description,
            },
            end_user_id=end_user_id,
            conductor_end_user_id=conductor_end_user_id,
            idempotency_key=idempotency_key,
            timeout=timeout,
            total_timeout=total_timeout,
            max_retries=max_retries,
            server_timeout=server_timeout,
        )
