# Code generated by packages/sdk-generator. DO NOT EDIT.
# Contract: packages/api-contract/generated/openapi.json (OpenAPI 3.1.0) sha256:3d102b7bcecbf18e72b655745e5c55d641457fab2fd8184b3da643aeb51bb76f
"""Generated resource classes. Reach them through the client, for example ``client.qbd.invoices``."""
